### ISSUE TITLE
RustDesk shouldn't capture the mouse movement if not active

### ISSUE THREAD

**Issue by Tragen** [rustdesk/rustdesk#1028]
**Describe the bug you encountered:**
I have RD running but it's not the active window/application.
When I move my mouse over the RD remote control window, the mouse moves on the remote computer also.

...

**What did you expect to happen instead?**
The mouse movement gets ignored when RD is not the active window.

...

**How did you install `RustDesk`?**
Windows Portable version

---

**RustDesk version and environment**
1.1.9
Windows 11 x64

**Comment by Cxxshyy** [comment]
i would like to take a look at this issue with some guidance

**Comment by wazerstar** [comment]
> i would like to take a look at this issue with some guidance

I can talk about how this issue is effected.

Having two multiple monitors as Remote, when you connect to another Machine, in this instance is Windows > Windows with nightly version.

Sometimes the mouse pointer insides Rustdesk is not drawn for you as Remote helper, you have to force mouse quickly over on the other monitor to see your actually mouse on your own screen, then put it back onto Rustdesk session to actually see the mouse pointer being drawn..

I dont know how to trigger it but it happens randomly and very often in sessions.

**Comment by rustdesk** [comment]
try out nightly build.

**Comment by rustdesk** [comment]
#3913
