### ISSUE TITLE
Modify screen resolution

### ISSUE THREAD

**Issue by itbencn** [rustdesk/rustdesk#1053]
The remote target I connect to is the `win10 server`. Usually, the system is inactive and does not support modifying the resolution. Moreover, the server system does not contain a graphics card program, and the default resolution is `800*600`.
Can you support changing the screen resolution like `sunlogin` or `todesk `or `mstsc`.

**Comment by rustdesk** [comment]
@fufesou lately we see a lot of such cases, the server does not have physical display (console), but have a virtual low resolution display. We do need to consider this case for our virtual display implementation. Also please check how todesk handle such case. is it virtual display or RDP session?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1029 similar.

**Comment by itbencn** [comment]
I don't know much about remote related technologies. After modifying the remote resolution through todesk, the resolution is always valid. Even if I disconnect and use rustdesk to connect, it is still the resolution of todesk.

**Comment by itbencn** [comment]
Although todesk supports setting the resolution, it still has some shortcomings. It can only be adjusted in limited fixed options, and it cannot be implemented as mstsc, which is the same as the resolution of the physical machine at the control end.
My own computer monitor is 4K (3840*2160) and then connected to a remote desktop with only 800*600. Obviously, it doesn't work.

**Comment by rustdesk** [comment]
I was talking to our dev.

**Comment by rustdesk** [comment]
We are screen capturing, not creating new session as what mstsc does. But in some special case (e.g. no physical display), we can create a virtual display with some resolution, but still impossible as flexible as mstsc. If you insist it, please our RDP sharing feature https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1173839858.

**Comment by itbencn** [comment]
Even if it can't be used flexibly like mstsc, I still hope rustdesk can be compatible with more resolutions to the greatest extent, which will bring a more perfect user experience.

**Comment by rustdesk** [comment]
Not feasible in short term, it is like rewrite RustDesk technically.

**Comment by itbencn** [comment]
okay, look forward to the more perfect rustdesk. Thank you for your reply.

**Comment by fufesou** [comment]
> Even if it can't be used flexibly like mstsc, I still hope rustdesk can be compatible with more resolutions to the greatest extent, which will bring a more perfect user experience.

As the rustdesk said, mstsc creates a virtual display, so it can change solutions with any values.
We have experimental  virutal display driver (IddDriver). There are some problems need to be solved, like Win ca signing.

Chaging physical monitor resolution is limited by the monitor.

**Comment by CliffHan** [comment]
> We are screen capturing, not creating new session as what mstsc does. But in some special case (e.g. no physical display), we can create a virtual display with some resolution, but still impossible as flexible as mstsc. If you insist it, please use our RDP sharing feature (Windows only on controlled side) [#914 (comment)](https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1173839858).

didn't see rdp option on windows version, here's what I got, did I miss something?

![image](https://user-images.githubusercontent.com/4934736/182874395-5eb7c8f4-1368-43fd-b519-9c55b5b869fb.png)

**Comment by autibequi** [comment]
Sure. It's nothing fancy. 

`sh
fast()
{
  gsettings set org.gnome.desktop.interface enable-animations false
  gnome-extensions disable $(gnome-extensions list | grep burn) # disable burn my windows
  xrandr --output DP-2 --mode 1920x1080 --scale 1.5x1.5
}

pretty(){
  gsettings set org.gnome.desktop.interface enable-animations true
  gnome-extensions enable $(gnome-extensions list | grep burn)
  xrandr --output DP-2 --mode 3840x2160 --scale 1.0x1.0
}
`

If the remote PC doenst have a monitor you could use a dummy HDMI connector (with a high max resolution) and lowers the resolution via a bat script to fit your need.

Kinda hack but I guess it would work.

**Comment by itbencn** [comment]
Take the liberty to ask
Is there any new progress on this issue
Rustdesk is great in every aspect, except for the resolution

**Comment by itbencn** [comment]
> 我们正在屏幕捕获，而不是像 mstsc 那样创建新会话。但是在某些特殊情况下（例如没有物理显示器），我们可以创建一个具有一定分辨率的虚拟显示器，但仍然不可能像 mstsc 那样灵活。如果您坚持，请使用我们的RDP共享功能（Windows仅在受控端）[#914（评论）。](https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1173839858)

It is mentioned in this sentence that rustdesk also creates a certain resolution for devices without a physical display to display. Can this resolution achieve several fixed options, such as 1920 * 1080, even though it is not as flexible as mstsc

**Comment by itbencn** [comment]
> We are screen capturing, not creating new session as what mstsc does. But in some special case (e.g. no physical display), we can create a virtual display with some resolution, but still impossible as flexible as mstsc. If you insist it, please use our RDP sharing feature (Windows only on controlled side) [#914 (comment)](https://github.com/rustdesk/rustdesk/issues/914#issuecomment-1173839858).

It is mentioned in this sentence that rustdesk also creates a certain resolution for devices without a physical display to display. Can this resolution achieve several fixed options, such as 1920 * 1080, even though it is not as flexible as mstsc

**Comment by rustdesk** [comment]
We do have a `virtual display` (Windows) implementation, but sadly, a virtual display driver is required to be installed, but we do not have EV license to install driver.

**Comment by itbencn** [comment]
> We do have a (Windows) implementation, but sadly, a virtual display driver (https://github.com/rustdesk/RustDeskIddDriver) is required to be installed, but we do not have EV license to install driver.`virtual display`

You can create a bootstrap program to let users who need to add certificate trust and install drivers

**Comment by rustdesk** [comment]
close in favour of #2423

**Comment by mengqin** [comment]
Hi @rustdesk  I found a workaround when you turn off your monitor and you want to adjust your resolution. Before I use this trick I can't change the resoltion, it's fixed in 1024 x 768. After I found it I believe you should can do some thing make rustdesk to adjust the resolution, becase this is just a setting operation on remote in fact, you can make it directly when you connect to the remote desktop. I'm on win10, I think this problem caused by the windows setting API, we know some setting not working in win 10 modern setting and can only work in legacy mode of configure windows. Please check this:

![image](https://github.com/rustdesk/rustdesk/assets/7312672/4ac6aeeb-35a5-45bc-8b4d-ab367abca96a)

This configure path is like this:

Under Windows 10:

Setting -> System -> Screen -> Scroll down right side configure and click on "Advance Dsiplay Setting" -> Click on "Monitor 1's Display Adapter Atttribute" -> Click on "List all mode" -> Select a resolution you like and click on "OK" and then "OK" to close all setting windows

After that you will found that your resolution is changed, and even don't need to change again next time you connected.

Here in fact, windows has a default display monitor called "Generic Non-PnP Monitor" take effect after you turn off all of your phyical monitor, you need to do is just set this one's resolution but not the real one. You even don't need a virtual monitor driver and you can do this thing. 

So I think this can also be done on software aspect, the only thing is to find the way to tune the resolution of  "Generic Non-PnP Monitor" and it will work.

Now I can operate my desktop without turn on the monitor to keep the resolution, this is great. 

Thanks your excellent software！
