### ISSUE TITLE
Operating system cloned to different computers always have same ID, and unable to control individual one.

### ISSUE THREAD

**Issue by sonicprogrammer** [rustdesk/rustdesk#1205]
**Describe the bug you encountered:**

I have an operating system deployed in one computer (with Rustdesk installed). Later, the operating system was cloned to other computer(s). As a result, all computers have the same ID. Can not control individual computer, as they all have a same ID. Try to uninstall Rustdesk & delete configuration file, but always generating same ID.

**What did you expect to happen instead?**

ID generation can be rerun manually, and generates different ID in different hardware.

**How did you install `RustDesk`?**

Downloaded 1.19 Windows x64 installation file from https://rustdesk.com/

**RustDesk version and environment**

Windows 11 21H2 Build 22000.795 x64

**Comment by simeononsecurity** [comment]
@sonicprogrammer If you cloned the systems without sysprepping, that is likely an issue.
This forces windows to regenerate many of the unique identifiers. 
Likely, you'll need to sysprep the image, and following deployment install rust desk as a work around.
@rustdesk 
The ability to regenerate the key and id should be implemented. Additionally, the process in which the id is derived should be documented.

**Comment by julianmaria** [comment]
Especially if the systems are domain joined. <-- false
Without sysprepping, you're likely to run into many other issues.  <-- false

https://community.spiceworks.com/topic/127247-windows-sid-and-guid-question-as-pertains-to-imaging-systems

The only ONE problem would be if and Infraestructure Administrator clones  a domain controller: the local / domain admin would have the same GUID between DCs (Nobody clones a DC)

**Comment by simeononsecurity** [comment]
> 

Just because something will work doesn't mean it's smart.
Microsoft recommends prepping all images meant to be cloned. 
Spiceworks is like the Wikipedia of technical information. I would never quote a forum.
The official answer is to sysprep. https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation?view=windows-11

**Comment by simeononsecurity** [comment]
Additionally, there are many issues with not sysprepping. Microsoft has come up with solutions to many of them. However third party software often relies on the unique identifiers that can only be changed by sysprepping. 
I'm not sure if rustdesk is using these for their identifiers, however teamviewer, mcafee HBSS, vmware (too many to list), and even nessus agents all rely on these unique identifiers in some part. 

You're correct in the fact it isn't smart to ever clone a DC.
However I've run into countless issues from both microsoft products and third party ones because of cloned SIDs. You can't tell me I'm wrong here.

**Comment by julianmaria** [comment]
There was a time when the Owner/programmer of sysinternals suite created NewSid for not needing to sysprep an image (Im talking of earlier 2003) (himself believed -as MS said- that it was necesary to recreate GUID / SIDS in any cloned system as u mentioned.)
Before Microsoft hired him to maintain the suite, he started a cruzade to analyze that myth. He discovered that the multiple Machine SIDs/GUIDS never are used in a domain to establish a difference between systems. 
I'm the infraestructure lead administrator of a huge network of a domains federation (since NT 3.51) we've have been deploying images since 1995 (no less than 50.000 systems).
You are right, sysprepp is what microsoft recommends & SIDs may be used by 3rd party software to difference bewteen systems. (very rare in my opinion as Ive seen 28 years working deploying systems).

**Comment by FlamingFlamingo42** [comment]
You can set custom IDs via script in USERPROFILE\AppData\Roaming\RustDesk\config\RustDesk.toml be sure to kill all rustdesk processes before and keep in mind, that this approach is user-based.

**Comment by Gigaion** [comment]
Duplicate IDs itself seems to be a problem on its own regardless of how the PC was setup/cloned.
Maybe instead the ID generation should involve a randomly generated salt? This would ensure the ID changes when initializing configuration.

The server itself should detect a duplicate ID and inform the client to report back a newly generated ID. Although this falls under a rustdesk-server bug category, so the salt suggestion remains.
