### ISSUE TITLE
Building rustdesk in docker container fails with error

### ISSUE THREAD

**Issue by miller45** [rustdesk/rustdesk#1226]
**Describe the bug you encountered:**
Build failed within docker compilation procedure
```
   Compiling protobuf-parse v3.1.0
   Compiling tokio-util v0.7.3
   Compiling parity-tokio-ipc v0.7.3-1 (https://github.com/open-trade/parity-tokio-ipc#20b28959)
   Compiling flutter_rust_bridge_codegen v1.30.0
   Compiling tokio-socks v0.5.1-1 (https://github.com/open-trade/tokio-socks#7034e792)
   Compiling protobuf-codegen v3.1.0
   Compiling scrap v0.5.0 (/home/user/rustdesk/libs/scrap)
   Compiling magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)
error: failed to run custom build command for `gstreamer-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/home/user/rustdesk/target/debug/build/gstreamer-sys-5bcfc80f31becbf7/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GSTREAMER_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GSTREAMER_1.0_STATIC
  cargo:rerun-if-env-changed=GSTREAMER_1.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gstreamer-1.0" "gstreamer-1.0 >= 1.10"` did not exit successfully: exit status: 1
  error: could not find system library 'gstreamer-1.0' required by the 'gstreamer-sys' crate

  --- stderr
  Package gstreamer-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-1.0' found
  Package gstreamer-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gstreamer-1.0' found

warning: build failed, waiting for other jobs to finish...
```
**What did you expect to happen instead?**
Build succeeding without error.

**How did you compile `RustDesk`?**
With these instructions from the README.md
``` 
git clone https://github.com/rustdesk/rustdesk
cd rustdesk
docker build -t "rustdesk-builder" .
docker run --rm -it -v $PWD:/home/user/rustdesk -v rustdesk-git-cache:/home/user/.cargo/git -v rustdesk-registry-cache:/home/user/.cargo/registry -e PUID="$(id -u)" -e PGID="$(id -g)" rustdesk-builder
``` 

The commit  hash at that time was `6c9e1e966b118c03299ca2859d573111527b2bb4`

Environment 
``` 
Docker version 20.10.17, build 100c701 
On Ubuntu 20.04.4 LTS
```

BTW: I am preparing a pullrequest with a working fix...

**Comment by rustdesk** [comment]
#763

**Comment by rustdesk** [comment]
> I am preparing a pullrequest with a working fix...

Thanks

**Comment by ericxuo** [comment]
Hi,

I get the same issue but I'm NOT using docker. Could you explain how to do to solve this issue ?
My (partial) commands : 

# setenv VCPKG_ROOT $HOME/vcpkg
# cargo run
...
   Compiling gdk-sys v0.16.0
error: failed to run custom build command for `gstreamer-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/home/eric/Téléchargements/rustDesk/rustdesk/target/debug/build/gstreamer-sys-5b9fc3fb8ffdd8a1/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GSTREAMER_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GSTREAMER_1.0_STATIC
  cargo:rerun-if-env-changed=GSTREAMER_1.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gstreamer-1.0" "gstreamer-1.0 >= 1.10"` did not exit successfully: exit status: 1
  error: could not find system library 'gstreamer-1.0' required by the 'gstreamer-sys' crate

  --- stderr
  Package gstreamer-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gstreamer-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gstreamer-1.0', required by 'virtual:world', not found
  Package 'gstreamer-1.0', required by 'virtual:world', not found

Regards.

Xuo.

**Comment by HPieniazek** [comment]
For people who, like me, have problems with packages in Windows.
Check out the Github Actions
