### ISSUE TITLE
appimage is not working

### ISSUE THREAD

**Issue by holequantum** [rustdesk/rustdesk#1243]
i tried on fedora 36 gnome and appimage is not starting. i was testing 1.19

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/577

**Comment by cooperbang** [comment]
Just for info: 
`./RustDesk-1.1.10-x86_64_1804.AppImage`

-> `/tmp/.mount_RustDeJm6xZn//usr/bin/rustdesk: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory`

The rustdesk AppImage doesn´t include libnsl.so.1 so it doesn´t run on Fedora Linux (libnsl.so.1 isn´t part of glibc since Fedora 28).

**Comment by holequantum** [comment]
okey.
