### ISSUE TITLE
Bitdefender flagging this as Malware

### ISSUE THREAD

**Issue by yodaphone** [rustdesk/rustdesk#144]
Tried to run this and bitdefender is flagging rustdesk as malware. i want to make sure before i whitelist this

**Comment by rustdesk** [comment]
false alarm

**Comment by HelmicNewciv** [comment]
Is there a way to flag that with them for review?  I'm imagining trying to walk a very tech-challenged person over the phone how to make an exception for Rustdesk after they reflexively clicked a button, trying to figure out what AV they are even using when they don't know enough to tell me, and dealing with their mounting frustration.

Flipside of that would probably be a big 'ole warning in the UI to make it clear they should *not* be allowing strangers to connect to their computer, especially those claiming to be tech support for Microsoft or whatever, right next to their ID and password so that they get a chance to get suspicious before they start reading things off.

**Comment by yodaphone** [comment]
according to Bitdefender you can submit sample for false positives

https://www.bitdefender.com/consumer/support/answer/40673/

I'll submit the file & lets see

**Comment by rustdesk** [comment]
> I'll submit the file & lets see

@yodaphone have you submit yet?

**Comment by mikbarbarton** [comment]
I'm having a similar issue when installing the Windows client.  Bitdefender doesn't let me install successfully.  Turned off virus scanner, installed, but as soon as I re-enabled virus scanner, it wiped the client.  Not sure how to add the exception.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/2485

**Comment by grummbeer** [comment]
closeable?

**Comment by rustdesk** [comment]
need to report to AntiVirus vendors one by one.

**Comment by rustdesk** [comment]
will do later, now we only focus on dev
