### ISSUE TITLE
microphone issue

### ISSUE THREAD

**Issue by danielecim** [rustdesk/rustdesk#1703]
Describe the bug you encountered:

When I connect to windows host with Audio input set to microphone:
if microphone properties are sample rate >= 48000Hz (in windows microphone properties), it works well.
if microphone properties are sample rate = 44100Hz (that is the default) I can't hear any sound.

What did you expect to happen instead?

Audio input works with 44100 HZ

How did you install RustDesk?

prebuilt binaries;

RustDesk version and environment

rustdesk Version 1.1.9
windows 10 client connecting to windows 10 host
ubuntu client connecting to windows 10 host
tried to connect via Direct IP access and via ID and Password

![rustdesk](https://user-images.githubusercontent.com/35593378/195299540-1c408c4d-c56d-4bfd-830f-164929d19349.png)

**Comment by rustdesk** [comment]
@21pages

**Comment by danielecim** [comment]
With a different host pc, Lenovo Thinkpad:

I can't hear System Sound and integrated microphone (AMD audio device).
Instead an external usb microphone (logitech webcam) works fine. So it's difficult to undertstand the origin of the problem.
Tried with windows 10 and linux as client, host window 10. In the image below host configuration:


![image](https://user-images.githubusercontent.com/35593378/195373480-154253c1-ce4b-4496-8294-1361fb586731.png)

**Comment by 21pages** [comment]
There may be a problem with the sample rate 48000, try this [build](https://github.com/21pages/tmp/blob/main/rustdesk-1.2.0-install.exe).

**Comment by danielecim** [comment]
Downloaded (10M), but installer doesn't start.

**Comment by 21pages** [comment]
I can't run it on win10 either, even compiling on win10, but it works fine on win11. BTW, I misunderstood your question, cpal convert 44100 to 24000, not 48000.

**Comment by Congyuwang** [comment]
Does the sample rate in 'sample rate >= 48000Hz (in windows microphone properties)' refer to sample rate on Host or Client?

**Comment by rustdesk** [comment]
it is on host side.

**Comment by rustdesk** [comment]
> Audio input works with 44100 HZ

it is on host side.

@rustdesk

 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
Leave a comment
未选择任何文件
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/rustdesk/rustdesk/blob/ba9d15597da0b9373d46a6616a2992a880a97b49/docs/CONTRIBUTING.md), [security policy](https://github.com/rustdesk/rustdesk/blob/ba9d15597da0b9373d46a6616a2992a880a97b49/docs/SECURITY.md), and [code of conduct](https://github.com/rustdesk/rustdesk/blob/ba9d15597da0b9373d46a6616a2992a880a97b49/docs/CODE_OF_CONDUCT.md).
Assignees
No one—
Labels
[bug](https://github.com/rustdesk/rustdesk/labels/bug)
Something isn't working
[help wanted](https://github.com/rustdesk/rustdesk/labels/help%20wanted)
Extra attention is needed
Projects
None yet
Milestone
No milestone
Development
 for this issue or link a pull request.
Notifications
Customize
You’re receiving notifications because you’re watching this repository.
4 participants
@21pages
@danielecim
@Congyuwang
@rustdesk
 
 Delete issue
Footer
© 2022 GitHub, Inc.
Footer navigation
[Terms](https://docs.github.com/en/github/site-policy/github-terms-of-service)
[Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
[Docs](https://docs.github.com/)
[Contact GitHub](https://support.github.com/?tags=dotcom-footer)
[Pricing](https://github.com/pricing)
[API](https://docs.github.com/)
[Training](https://services.github.com/)
[Blog](https://github.blog/)
[About](https://github.com/about)
Owner rustdesk commented now it is on host side.

**Comment by Xerxes-2** [comment]
Tested in my machine 
Build: Latest master branch
Host: Windows 11 22H2
Client: iPad OS 16.1
Sound works fine on 2ch, 16-bit, 44100Hz
but doesn't work on 24-bit
![image](https://user-images.githubusercontent.com/35587143/203294581-d6cc20b0-6a78-4991-811d-ecf65f1a6fae.png)

**Comment by rustdesk** [comment]
We did not support 24 bit,

https://github.com/rustdesk/rustdesk/blob/42d17f9d2bd3a0ec2b39623290da44bf020b90f0/src/server/audio_service.rs#L246

Could you help add 24 bit support?

**Comment by rustdesk** [comment]
#3762
