### ISSUE TITLE
Audio not heard from Win11 remote machine

### ISSUE THREAD

**Issue by Eruthon** [rustdesk/rustdesk#2018]
**Describe the bug**
When logging into remote machine running Win11 22H2, I can't hear sound from the remote machine on either client Win11 22H2 or my Android phone.

**Describe the environment**
 - Install environment: self-host server on Win Server 2019, clients {Win11 22H2, Android 12}, remote machine Win11 22H2

**How to Reproduce the bug**
1. Connect to remote machine running Win11 22H2
2. Play sound on remote machine
3. Can't hear the played sound

**Expected behavior**
I should hear the sound as I do with Win10 remote machines.

**Additional context**
Tried it on 2 Win11 22H2 clients and 2 Win10 clients.

**Notes**
Started to play with Rustdesk a few days prior. Absolutely amazing software expect this happens and I can't figure it out.

**Comment by Eruthon** [comment]
Okay, fixed it - seems like problems with Voicemeeter software, will try to tweak it a bit. For now I disabled all its virtual outputs and inputs.

**Comment by rustdesk** [comment]
Thanks,

as ref: https://github.com/rustdesk/rustdesk/issues/1086

**Comment by rustdesk** [comment]
closr to favor #1189

**Comment by rustdesk** [comment]
#3762

**Comment by envico801** [comment]
I can confirm that the error can occur when using Voicemeter. This software adds several virtual speakers/microphones, and even if the correct audio output is selected (the computer's default speakers, for example), it can cause RustDesk to fail to share the computer's audio. It is not a RustDesk error. The error occurs when you have one or more audio output devices (virtual or otherwise).

This image shows how I have one of these audio outputs enabled, which is what causes the error, but it should be noted that in addition to this, I have the PC speakers set to default, but it still fails.
<img width="476" height="492" alt="Image" src="https://github.com/user-attachments/assets/7430f17b-1042-4c99-b71d-6149b3027a23" />

**The solution is simply to disable the other audio output devices or select the correct/default one before starting RustDesk. Doing so after the program has started will cause it to continue to fail, and you will have to restart RustDesk (close it and reopen it completely)**.
