### ISSUE TITLE
Install button not work on remote screen

### ISSUE THREAD

**Issue by mehdi-song** [rustdesk/rustdesk#2083]
**Describe the bug you encountered:**

Hello
sorry for bad English language,
after remote with RustDesk , on remote client i can't select install button and if require administrator access , i can't enter username and password to install .

**What did you expect to happen instead?**

i can select install button and enter administrator username and password.

**How did you install `RustDesk`?**

install  Releases 9 - 1.1.9 Latest and my own server on windows

---

**RustDesk version and environment**

Install server on windows server 2019 with default parameters .
test on windows 10 
cpu core i5 6500
12 gigabyte ram
apacer ssd 256gigabyte for windows Drive

**Comment by djex** [comment]
On the remote side you need to enable "Enable remote configuration modification" in the settings in order to click the Install button. However this will UAC prompt the remote user for administrative access. There currently is no way to enter administrative credentials to skip the UAC prompt. Hopefully this feature will get added at some point.

**Comment by rustdesk** [comment]
duplicate issue
