### ISSUE TITLE
[mac os x] full screen can not do keyboard input

### ISSUE THREAD

**Issue by congzhangzh** [rustdesk/rustdesk#2514]
**Describe the bug you encountered:**
can not input something when fullscreen on mac os x 
...

**What did you expect to happen instead?**
keyboard input works
...

**How did you install `RustDesk`?**

---

**RustDesk version and environment**
the latest version

but, if you drag a terminal app window(other should work too?) to split the fullscreen, the input works again!

**Comment by rustdesk** [comment]
video please, no idea what are u saying

**Comment by gsv2003** [comment]
I have same trouble with connection from MacOS to Win-machine. Keyboard doesn't work anyway =(

**Comment by congzhangzh** [comment]
You can fullscreen it first and then drag a terminal app to split screen with it, then it works

**Comment by gsv2003** [comment]
> You can fullscreen it first and then drag a terminal app to split screen with it, then it works

I saw your solution, but it doesn't work for me 🤷🏻‍♂️

**Comment by rustdesk** [comment]
> Keyboard

https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1250047560

**Comment by gsv2003** [comment]
> > Keyboard
> 
> @gsv2003 [#974 (comment)](https://github.com/rustdesk/rustdesk/issues/974#issuecomment-1250047560)

🔥thank you so much!!!!

**Comment by congzhangzh** [comment]
works, tks @rustdesk

**Comment by kholis** [comment]
Hi @congzhangzh 

I still have this issue. Window focus lock on rustdesk in fullscreen mode (new spaces/desktop)

I've enabled:
`System Preferences -> Security & Privacy -> Input Monitoring -> Unlock the lock on the bottom left -> Add apps -> Select the app -> Check the box left to it`

When I change to primary Space, I cannot written any input because Window active is still in rustdesk in next Space.

Any workaround? Thanks.
