### ISSUE TITLE
Global Settings Control

### ISSUE THREAD

**Issue by rustdesk** [rustdesk/rustdesk#3101]
### Discussed in https://github.com/rustdesk/rustdesk/discussions/3093

<div type='discussions-op-text'>

<sup>Originally posted by **duczz** February  6, 2023</sup>
It would be great when we can control the rustdesk settings (z.b. directaccess) via regkey, copy config files or install parameter.
Currently rustdesk overwrite the copyed new settingsfile on startup</div>

**Comment by kapytanhook** [comment]
this also affects me, seems very hard to do in ubuntu as it keeps overwriting manually placed config files

**Comment by duczz** [comment]
@rustdesk Any News? The settingsfile will be overridden when i start on the rustdesk service on windows

**Comment by dzatoah** [comment]
Heyo, I'm very new to Rustdesk. Is there any documentation about manually placed config files? This would be very handy since then you can preconfigure costumer's Rustdesk (for example with a company-wide Relay/ID-Server).

Also is there any way to "block" certain settings? (For example block the UI from enabling direct IP support, LAN discovery, File Transfer...) Should I create a new issue for this feature-request (if it isn't already there).

**Comment by PenthouseLA** [comment]
@rustdesk  any news about it?

**Comment by AHA1GE** [comment]
Interested too

**Comment by jamiegau** [comment]
please.

**Comment by rustdesk** [comment]
close this since we have custom client feature.

https://twitter.com/rustdesk/status/1788905463678951787?t=G0DEhYLYYfALeiUoUFwY7A&s=19
