### ISSUE TITLE
Whether to support multiple monitors

### ISSUE THREAD

**Issue by xiaoshengduan** [rustdesk/rustdesk#313]
Whether to support multiple monitors like freerdp /multimon   or mstsc winposstr

**Comment by rustdesk** [comment]
PR please if possible.

**Comment by rustdesk** [comment]
Will, but low prioirity.

**Comment by lukebarone** [comment]
Currently, I see the monitor selector at the top of the connection window. Clicking on [2] shows a blank second screen, even if I know there is something on it.

Suggest we remove the screen selector if it's not currently supported?

**Comment by rustdesk** [comment]
> screen selector

1.1.9?

**Comment by lukebarone** [comment]
> > screen selector
> 
> 1.1.9，windows?

Yes

**Comment by t-oster** [comment]
I also would vote for the possiblity to open different screens in differnt windows, so I can reproduce a multi-monitor setup with local screens.

**Comment by wizzyto12** [comment]
> 

We have just switched from anydesk to rustdesk and this is the show stopper feature for us. Looking forward to see support for this.

**Comment by rustdesk** [comment]
> selector

it should work, at least it works on my multiple monitors

**Comment by wizzyto12** [comment]
> 

in my case, on windows 11, trying to open a second RustDesk and switching the monitor actually switches on both sides (so I can always see one remote). Am I doing something wrong?

**Comment by mlagos** [comment]
> > 
> 
> in my case, on windows 11, trying to open a second RustDesk and switching the monitor actually switches on both sides (so I can always see one remote). Am I doing something wrong?

I have the same problem.

**Comment by Evengard** [comment]
Don't know if it is related...
I have kind of a similar problem. When I switch to the second monitor, it just shows a smaller portion of the screen from the first one.

Now, I have a guess why is that. My first monitor is 2560x1440, my second one is 1920x1080, and it seems like it shows the correct resolution (1920x1080) but of the wrong monitor.

Now, my monitors are organized such as the second monitor is at the left from the first (and primary) one. This means that it's coordinates are negative (aka it's leftmost topmost coordinate is actually -1080, 0 instead of 1440, 0 if it would be on the right side). It may be, that RustDesk doesn't like negative coordinates and clamps them to 0, hence we get the wrong coordinates of the displayed area.

**Comment by Evengard** [comment]
Update - apparently inputting the device name into the "driver" parameter is actually correct for a display. With one caveat though:

> If lpszDriver is DISPLAY or the device name of a specific display device, then lpszDevice must be NULL or that same device name. If lpszDevice is NULL, then a DC is created for the primary display device.

Here, we got it NULL, so as described, we're getting the primary display device NO MATTER which display device we specified in the driver name!

We should pass the same parameter for both parameters to get actually another device, it seems, smth like:

```csharp
let screen_dc = CreateDCW(&name[0], &name[0], 0 as _, 0 as _); 
```

**Comment by Evengard** [comment]
Another solution would just pass the DEVMODEW structure instead (we got it anyway when querying, we could just add it to the Display object anyway instead or alongside the name - I'll assume it was added).

I'm not familiar with Rust, but it should look smth like this:

```rust
let screen_dc = CreateDCW(0 as _, 0 as _, 0 as _, devmode); 
```

**Comment by rustdesk** [comment]
close to favor #486

**Comment by rustdesk** [comment]
Ready in nightly build now. https://twitter.com/rustdesk/status/1714199082640581039
