### ISSUE TITLE
How to enable the inline feature in the code?

### ISSUE THREAD

**Issue by fy2462** [rustdesk/rustdesk#321]
Hi @rustdesk .

I found I can not enable the inline feature in vscode. How to enable it.
Should I modify the `Cargo.toml`? 
I must copy all src/ui/* files in rustdesk binary folder now, the binary can work well.

BTW, I add the `inline` in the default features: 

`default = ["use_dasp", "inline"]`

But, the compiler output:

```rust
error[E0583]: file not found for module `inline`
 --> src/ui.rs:3:1
  |
3 | mod inline;
  | ^^^^^^^^^^^
  |
  = help: to create the module `inline`, create file "src/ui/inline.rs" or "src/ui/inline/mod.rs"
```

thanks very much.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/240

**Comment by fy2462** [comment]
Thansk, Got it.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/build.py

**Comment by shujaat-github** [comment]
It is very easy to enable inline feature. By default, all features are disabled unless explicitly enabled. To enable a feature you need to add comma separated `"feature_names"` in the `default `section of the `feature `section. In your case, you need to add `"inline"` in the `default `section:

```
[features]
inline = []
hbbs = []
cli = []
with_rc = ["simple_rc"]
appimage = []
use_samplerate = ["samplerate"]
use_rubato = ["rubato"]
use_dasp = ["dasp"]
hwcodec = ["scrap/hwcodec"]
default = ["use_dasp", "inline"]
```
Before building RustDesk, run `inline-sciter.py` script which automatically generates ` inline.rs` file in `rustdesk/src/ui ` which is required once you enable `inline `feature otherwise build will fail.
