### ISSUE TITLE
[Bug] Screen Recording permission invalid on macOS (waiting for image)

### ISSUE THREAD

**Issue by wakewon** [rustdesk/rustdesk#3261]
### Bug Description

Rustdesk v1.2.0 cannot be granted with Screen Recording permission even the option in system preferences is enabled. When accessed by another device (to be the remote side), display on local side is in all black (it seems that the Accessibility permission is also invalid).

### How to Reproduce

1. Install / Update to Rustdesk v1.2.0.
2. Configure Screen Recording permission.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/40191996/219851999-1fe047e2-a2d9-4a00-84da-d728775413e6.png">

4. Disable Rustdesk's permission.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/40191996/219852111-831252d9-3a90-41d3-940f-5854c96b553a.png">

6. Restart Rustdesk ( `com.carriez.RustDesk_service.plist` is unloaded #3260 ).
7. Grant Rustdesk's permission
8. Restart Rustdesk.
9. Still require to grant Screen Recording permission.

### Expected Behavior

Permisson notice disappeared and display on the controller works well.

### Operating system(s) on local side and remote side

iOS / iPadOS / Windows -> macOS 13.2.1

### RustDesk Version(s) on local side and remote side

1.1.10 / 1.1.10 / 1.2.0(Build Date: 2023-02-18 00:32) -> 1.2.0(Build Date: 2023-02-18 00:20)

### Additional Context

Other helpless attempts:
- Grant permission and reboot (without unload `com.carriez.RustDesk_service.plist` ).
- Remove Rustdesk permission item and grant again, then restart the app.
- Reset permission `tccutil reset ScreenCapture com.carriez.RustDesk` and reboot.

**Comment by rustdesk** [comment]
Everything works well on my M1.

**Comment by rustdesk** [comment]
Hope you can help us figure it out.

**Comment by wakewon** [comment]
> It works well on my M1 (13.1). Frankly, I do not know how to help you.

Well mine is an ancient Intel……

Maybe later I will try again on another Intel device without rustdesk installed, or fully reset Screen Recording permission for all apps.

**Comment by wakewon** [comment]
After fully uninstall & cleanup & reinstall 1.2.0(Build Date: 2023-02-19 00:17), together with removing the Rustdesk permission item and grant again, this issue disappeared.

It might be an update issue since this issue happened after I update my Rustdesk from 1.1.9 to 1.2.0(Build Date: 2023-02-18 00:20).

**Comment by rustdesk** [comment]
Thanks

**Comment by ThomasWaldmann** [comment]
I installed latest daily and it asks me again and again for screen permission, even if i grant / remove / grant them in system settings.

**Comment by frosn0w** [comment]
+1, M1 MBP, MacOS Ventura 13.2.1

**Comment by zhangbo8418** [comment]
Now it does exit, but how do I open the window?

**Comment by rustdesk** [comment]
> I installed latest daily and it asks me again and again for screen permission, even if i grant / remove / grant them in system settings.
> 
> M1 MBA, macOS Ventura 13.2.1.

I encountered the same issue, I did grant / remove (with the `-` button)  twice or tripple to make it work. It embrassed me also, but I still have no solution to resolve this.

**Comment by wakewon** [comment]
Here are some suggestions to solve this problem:

1. Full removal + reinstall rustdesk (`AppCleaner.app` may help).
2. Remove Rustdesk permission item and grant again, then restart the app.
3. Reset screen recording permission for all apps: execute `tccutil reset ScreenCapture` in Terminal.app.
4. Reset Accessibility permission for all apps: execute `tccutil reset Accessibility` in Terminal.app.
5. Reboot, and grant this two permission for rustdesk.

You may try to reset the two permissions for rustdesk only before step 2 and 3:
```
tccutil reset ScreenCapture com.carriez.rustdesk
tccutil reset Accessibility com.carriez.rustdesk
```
Reboot is still required.

> Reset permissions only for rustdesk doesn't work for me.
> Full removal + reinstall rustdesk, then remove the previous permissions works for me.

**Comment by foss-** [comment]
Executed both commands
```
tccutil reset ScreenCapture com.carriez.rustdesk
tccutil reset Accessibility com.carriez.rustdesk
```
rebooted intel mac.

RustDesk asked for the various permissions as expected and it seemed to remember them (Screencapture, Accessibility) but Input Monitoring keep going in circles. RD shows Permissions request, open System Settings. Disable, Re-Enable Permission, restart RD, still asking for Input Monitoring permission.

Is there another command availabel to reset InputMonitoring as well?
`tccutil reset InputMonitoring  com.carriez.RustDesk` did not work:
`tccutil: Failed to reset InputMonitoring approval status for com.carriez.RustDesk`

**Comment by ThomasWaldmann** [comment]
@rustdesk so, what did fix it? can you give a link?

**Comment by rustdesk** [comment]
We have no resolution for this, because we can not reproduce on our Macs.

**Comment by godzfire** [comment]
Has anyone on an Intel Mac OS Monterey 12.x got nightly builds to work with this issue?

**Comment by godzfire** [comment]
Has anyone else encountered this?

**Comment by Majoraslayer** [comment]
> Has anyone else encountered this?

July 1st, 2023 I'm having this same issue.  I've created 3 Mac OS virtual machines (under Ubuntu), with different versions of Mac OS, and all have had this same problem with RustDesk.  I'm currently using Mojave, which lacks a setting in the control panel security options, to allow or deny permissions for screen recording.  Changing this in other versions made no difference anyway.  Every time I try to remote to the VM, it gets stuck at "Connected, waiting for image...".  If it's at all relevant, I'm self-hosting the RustDesk server.

**Comment by foss-** [comment]
@Majoraslayer keep in mind that vms have additional issues on top of the permission issue being discussed here. In order to reduce complexity and allow for better test results not using vms is probably a good idea.
To get an idea of the issues related to vms see https://github.com/rustdesk/rustdesk/issues/4357 which is specific to vmware vms issues. I am pretty sure other vms have similar issues.

**Comment by foss-** [comment]
Since another commit trying to resolve this is part of 1.2.1, retested on macOS 13.4.1.
- removed RustDesk from `System Settings > Privacy & Security > Input Monitoring`
- re-opened RustDesk
- was greeted with Permissions info recommending to install background service
- added that and was informed `Background Items Added
Software from "zhou huabing" added items that can run in the background. You can manage this in Login Items Settings.`

Curiously RustDesk is not requesting additional permissions despite me removing the Input Monitoring permission. I would think that is unexpected behavior. When I double checked `Input Monitoring` permissions, there was no RustDesk entry (as expected). However I am wondering, shouldn't RustDesk be requesting this permission then?

Briefly tested this on macOS Monterey 12.6.7 mac of a friend and there the permission dialog never vanished even after removing and re-adding both Login Item and Input Monitoring Permission. After re-adding both and restarting RustDesk 1.2.1 it still is requesting Permissions. When trying to grant the requested permission, System Settings > Privacy and Security > Accessibility Controls` but RustDesk is already on the list and enabled.

No matter the permissions I am still unable to control the remote macOS 12 mac with my mouse. https://github.com/rustdesk/rustdesk/discussions/4871

Unrelated: Would renaming the login item to `RustDesk` be possible?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/4871#discussioncomment-6578012

**Comment by justinnichols** [comment]
Yeah, https://github.com/rustdesk/rustdesk/discussions/4871#discussioncomment-6578012 didn't work for me.  I'm on macOS Ventura (13.5) (late 2019 MBP, Intel) and I cannot get the pink Permissions UI to go away at all.  I have disabled Accessibility and Screen Recording (Input Monitoring doesn't have one), then rebooted, then re-enabled them, then launched RustDesk and it still shows the pink Permissions UI.

**Comment by wriver0s** [comment]
So i managed to fix it by manually removing the permisions and manually selecting the apps using the "+" and "-"
you first need to deselect the given permissions and the delete it using the "-" button. Then add the rustdesk app using the "+" button

**Comment by i6941** [comment]
> Referen

I tried with
tccutil reset ScreenCapture com.carriez.RustDesk
tccutil reset Accessibility com.carriez.RustDesk

It works for me

**Comment by pol-multar** [comment]
> > Referen
> 
> I tried with tccutil reset ScreenCapture com.carriez.RustDesk tccutil reset Accessibility com.carriez.RustDesk
> 
> It works for me

Hello, 
this worked for me aswell on M2 + Sonoma 14.1.1

**Comment by Priestgold9** [comment]
https://github.com/rustdesk/rustdesk/issues/3261
