### ISSUE TITLE
Export/import settings and connections via UI

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3269]
### Description

Ability to export/import settings and connections via the UI when you need to reinstall RustDesk or transfer data to another device.

### Impact

Now on Windows, for example, they can be found in `%userprofile%\AppData\Roaming\Rustdesk\config`, but on each platform they are stored in different places (usually in hidden folders), so they are quite difficult to find. It would be nice to be able to export/import all settings and separate connections in the RustDesk Settings.

**Comment by grummbeer** [comment]
You can export the config,

![rustdesk-notification-current](https://user-images.githubusercontent.com/67791701/219900340-53e68d75-bd39-4ab5-9f6d-49c53b4129ee.png)

- Instead showing this message, a clearly visible notification should appear (in a defined "notification area") that clearly informs what has happened and where the file is stored.
  
     [ Your configuration has been sucessfully exported … to /home/user/… (link: open) ]

- The actions should be represented as a buttons, in same row as "apply" because there are the second class siblings of the first class action "apply"

**Comment by rakleed** [comment]
@grummbeer I know about the possibility of importing the server config, but I write in an issue about RustDesk settings and connection devices.

**Comment by rustdesk** [comment]
#2911 #2854

**Comment by cstrickjacke** [comment]
> Where does the exported settings file reside for Windows and Ubuntu clients?

In your clipboard after clicking that button. You need to paste it somewhere yourself
