### ISSUE TITLE
Linux crash if flutter texture render is enabled

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#3343]
### Bug Description

Establish a connection, the client side may crash and report the following message.

```
(rustdesk:15689): Gdk-ERROR **: 22:39:06.529: The program 'rustdesk' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadFence'.
  (Details: serial 2364 error_code 136 request_code 135 (SYNC) minor_code 17)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

### How to Reproduce

1. Build the source code and run `flutter run -d linux`.
2. Connect the a peer.

This issue is not easy to reproduce. For most time, the process dose not crash.

### Expected Behavior

Do not crash.

### Operating system(s) on local side and remote side

Linux -> Win10

### RustDesk Version(s) on local side and remote side

ngihtly -> nightly

### Screenshots

![image](https://user-images.githubusercontent.com/13586388/220941746-27a98886-6202-40e9-8fcf-3e8a52407d14.png)

### Additional Context

Response from chatGPT

The error message suggests that the program 'rustdesk' received an X Window System error due to a "BadFence". This error is likely related to a synchronization object called a "fence" in the X Window System.

Fences are used to synchronize access to shared resources between multiple clients or processes that are running on the X Window System. A "BadFence" error can occur when a client tries to access a fence that has been deleted or is otherwise invalid or corrupt.

To debug the error, you can try the following:

1. Check the code that creates and manages fences to ensure that they are properly initialized and used.
    
2. Check whether there are any known issues or limitations related to fences in the version of the X Window System or window manager that you are using.
    
3. Use a debugger to step through the code and inspect the values of the fence objects and related variables.
    
4. Check whether there are any conflicting or overlapping uses of fences by other clients or processes that are running on the X Window System.

Once you have identified the cause of the error, you can take steps to fix it. This may involve correcting the code that creates and manages fences, modifying the way that the program interacts with the X Window System or window manager, or addressing any conflicts or issues related to shared resources or synchronization.

**Comment by rustdesk** [comment]
#763

**Comment by fufesou** [comment]
The actual reason may be the corroption of flutter texture and multi-window-manager.
Close as currently do not use texture render on Linux.

**Comment by cuibonobo** [comment]
@fufesou I'd like you to consider reopening, since this is still reproducible on a current release, despite
the issue being closed on the premise that texture render isn't used by default on Linux.

**Version:** RustDesk 1.4.9 (Flatpak) — `use-texture-render` was **on** (the default in
this build), not manually enabled by me.

**Impact:** this isn't just a client-side crash — it took down the entire GNOME Shell
compositor, requiring a full session/VM reboot to recover (not just restarting RustDesk).

**Setup:** GNOME Shell 50.3 (Wayland), NVIDIA open kernel modules 610.43.03, RTX 2070 SUPER
(GPU passthrough into a QEMU/KVM VM), Fedora Atomic 44 (Bluefin), kernel 7.0.12-201.fc44.

**Sequence from journalctl:**
```
11:05:22  RustDesk launched, connected to a remote peer
11:05:31  create pixelbuffer texture: peerId: ..., textureId: ...
11:05:43  [Main] call hide ... / dispose session ... / model closed
11:05:43  destroy pixelbuffer texture: peerId:  display:0, textureId:...
11:06:25  at-spi2-registryd: Disabling unresponsive app with pid <gnome-shell>
11:06:25  at-spi2-registryd: Disabling unresponsive app with pid <rustdesk>
```

From that point the compositor never recovered (mouse/keyboard input stopped working,
screen was frozen) while the rest of the OS (kernel, NetworkManager, qemu-guest-agent)
stayed fully responsive, so it's specifically the Wayland compositor wedging, not a
kernel/GPU-driver-level hang. I had to trigger a VM reboot from the hypervisor side;
systemd had to SIGABRT the gnome-shell process because it wasn't responding to SIGTERM:
```
org.gnome.SettingsDaemon.XSettings.service: State 'stop-sigterm' timed out. Aborting.
org.gnome.Shell@user.service: State 'stop-sigterm' timed out. Aborting.
org.gnome.Shell@user.service: Main process exited, code=dumped, status=6/ABRT
```

I have manually set `use-texture-render = 'N'` in `RustDesk_local.toml` after the fact in 
hopes that this doesn't happen again. 

If the intent is for Linux to default to texture-render off, that
default doesn't seem to be reaching 1.4.9 — might be worth double-checking whether it
shipped, or whether this needs reopening for the non-default-changed release line.

**Comment by fufesou** [comment]
Thanks for the detailed report.

You're right about the default: on Linux, 1.4.9 treats texture rendering as enabled unless `use-texture-render` is explicitly set to `N`.

The earlier statement that texture rendering is off by default on Linux is not true for 1.4.9.

However, I don't think we should reopen this issue unless the same X11 `BadFence` crash is reproduced. #3343 is specifically about RustDesk crashing with `BadFence`. 

What you saw is GNOME Shell hanging under Wayland, and I haven't been able to reproduce it. The create/destroy messages confirm that the texture path was used, but they don't show that the texture's destruction caused the compositor to hang. The destroy message is logged after `closeTexture()` returns, and a responsive guest does not rule out a graphics-driver stall.

Please open a new issue for this problem.

The system details you've already provided are excellent. It would also help to include the host OS, QEMU/KVM and libvirt versions, the VM graphics configuration, the GPU passthrough setup, and the exact steps leading up to the hang.

For comparison, I haven't reproduced it on my VirtualBox on a Windows host, but I don't have NVIDIA graphics cards connected:
1. Ubuntu 24.04, Gnome
2. Ubuntu 26.04, Gnome
3. Fedora 44, Gnome, GNOME Shell 50.0 (Wayland)

**Comment by cuibonobo** [comment]
Opened #16006.
