### ISSUE TITLE
Active password input field when connecting is incorrectly aligned

### ISSUE THREAD

**Issue by rakleed** [rustdesk/rustdesk#3365]
### Bug Description

The active password input field when connecting is incorrectly aligned.

### How to Reproduce

1. 1. Set a password on the remote device
2. Connect to a remote device

### Expected Behavior

When you click on Password, the input field that appears is properly aligned.

### Operating system(s) on local side and remote side

macOS 13 → Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

![Screenshot 2023-02-24 at 23 37 47](https://user-images.githubusercontent.com/19418601/221286853-bf59c8ea-94e0-49fc-b46d-28b9e4c46973.png)

![Screenshot 2023-02-24 at 23 37 54](https://user-images.githubusercontent.com/19418601/221286860-3c64a3c8-4805-40f1-84f8-c07c6a859289.png)

**Comment by rakleed** [comment]
@rustdesk why is the report invalid?

@grummbeer could you take a look?

**Comment by grummbeer** [comment]
rustdesk is the chief :)

Since you ask me, i already noticed the same. Plus …

- space between input (checkox) and its label is too large
- TextInput is bordered on desktop
- placeholder is a bit too much (too much things on small space), because the dialog is self descripted and the floating label is enough. Maybe the label could be "Enter your password" 

To be clear, I don't intend to do anything that doesn't conform to rustdesk. I couldn't at all :)

**Comment by rustdesk** [comment]
> * space between input (checkox) and its label is too large
> * TextInput is bordered on desktop
> * placeholder is a bit too much (too much things on small space), because the dialog is self descripted and the floating label is enough. Maybe the label could be "Enter your password"

Totally agree.
