### ISSUE TITLE
ailed to run custom build command for `magnum-opus v0.4.0

### ISSUE THREAD

**Issue by zhangzdc** [rustdesk/rustdesk#371]
error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)`

Caused by:
  process didn't exit successfully: `/home/zdc/rustdesk/target/debug/build/magnum-opus-0f355b5005a20765/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=x64-linux
  cargo:rustc-link-lib=static=opus
  cargo:rustc-link-search=/root/vcpkg/installed/x64-linux/lib
  cargo:include=/root/vcpkg/installed/x64-linux/include
  rerun-if-changed=/root/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/opus_ffi.h
  rerun-if-changed=/root/vcpkg/installed/x64-linux/include

  --- stderr
  /root/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found
  /root/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /root/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/build.rs:66:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/19

**Comment by Programmist-AZ** [comment]
Здравствуйте, Проблема сохраняется. Как при компиляции решить ее?

error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/rustdesk/magnum-opus#5cd2bf98)`

Caused by:
  process didn't exit successfully: `C:\Users\ARTEM\.vscode\rustdesk-master\target\release\build\magnum-opus-145ed4985965f575\build-script-build` (exit code: 101)
  --- stdout
  cargo:info=x64-windows-static
  cargo:rustc-link-lib=static=opus
  cargo:rustc-link-search=C:\vcpkg\installed\x64-windows-static\lib
  cargo:include=C:\vcpkg\installed\x64-windows-static\include
  rerun-if-changed=C:\Users\ARTEM\.cargo\git\checkouts\magnum-opus-4bb999f3bcbf6ab0\5cd2bf9\opus_ffi.h
  rerun-if-changed=C:\vcpkg\installed\x64-windows-static\include
