### ISSUE TITLE
Mouse randomly gets stuck until moved and click and drag won't release

### ISSUE THREAD

**Issue by larryqiann** [rustdesk/rustdesk#3819]
### Bug Description

I am using the latest nightlies of RustDesk as of the creation of this post. The connection is successful, between macOS Ventura and Ventura machines (M1 host, intel client) but there are two problems with the mouse:

1) The mouse will get "stuck". 
2) The mouse will get stuck on the "click and hold/drag" mode.

Thanks

### How to Reproduce

1)

To reproduce, first enable "show remote cursor" to make the cursor more visible. Connect to the remote machine, preferably over the Internet, and move the mouse in circles. Sometimes, the mouse is jumpy, but the mouse generally follows the client. Play a video on the remote computer to show that the video is continuous and smooth.

Next, move the mouse intermittently. Notice that in some cases, the remote cursor no longer follows the local cursor, until you move the cursor a bunch, then it catches up.

2) 

To reproduce, do some dragging of a window in the session around. Play a video to show the connection is continuous. Sometimes, click and drag will get stuck, and releasing the mouse button does not release it on the remote computer. The drag does not get released even when clicking on other stuff in the local computer or the RustDesk application window and must be released with repeated clicking.

### Expected Behavior

1) The expected behaviour is that the mouse of the remote computer will follow the local computer at all times when the mouse cursor is inside the window of the remote computer.

2) The expected behaviour is that the mouse click will be released according to the local mouse click, or at least, a timeout implemented.

### Operating system(s) on local side and remote side

macOS Ventura Intel > macOS Ventura M1

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

https://user-images.githubusercontent.com/25872705/228324446-b23e8d69-b8c7-4658-850b-f750e8fed80c.MP4

https://user-images.githubusercontent.com/25872705/228324723-88f185f8-9fd3-4f81-a28d-cde823acf0f6.MP4

**Comment by rivalcomp** [comment]
I also have this issue on all supported Windows version clients. The client side mouse pointer does not follow the control side movement and the clicks. You can test it well by randomly right clicking on the desktop. You will see that the context menu will show up at a totally different place than it should be. It's not a lag, because if you wait for a longer period of time without moving the mouse, the mouse pointer won't be at the right place, the context menu will show up at the same wrong place (or it won't pop-up because the client doesn't get the click action at all), so the pointer just stays at some previous wrong position forever. You have to move the mouse a little bit at the same position to put the client mouse pointer to the right place. Or you have to click again to release a drag-and drop action. 1.2.0 is unusable on Windows clients. Because of my work I've tested it on many-many Windows clients, and 1.2.0 on the client side is unusable.

Windows 10 -> Windows 11, 10, 7 clients
---------------------------------------------
1.1.9 -> 1.2.0 doesn't work
1.2.0 -> 1.2.0 doesn't work
1.1.9 -> 1.1.9 OK
1.2.0 -> 1.1.9 OK

Linux Mint Control -> Windows 11, 10, 7 clients
----------------------------------------------------
1.2.0 -> 1.2.0 doesn't work
1.2.0 -> 1.1.9 OK

Windows 11, 10 control -> Linux Mint client
-------------------------------------------------
1.1.9 -> 1.2.0 OK
1.2.0 -> 1.2.0 OK


So something might be wrong with the Windows client side 1.2.0.
I'm using self hosted rustdesk-server 1.1.7-1 (not relevant, the problem also remains using the official servers).

**Comment by rustdesk** [comment]
@fufesou

**Comment by rustdesk** [comment]
@rivalcomp tell us more about your monitor plese, resolution and zoom factor etc.

**Comment by rustdesk** [comment]
@zhangbo8418 do you have similar cases?  https://github.com/rustdesk/rustdesk/issues/4261

**Comment by rustdesk** [comment]
@larryqiann have you tried on the other non-mac machines? Frankly, we have no two macs to test.

**Comment by rustdesk** [comment]
The mouse control priviledge implementation causes many issues. We may consider to remove it.

**Comment by rustdesk** [comment]
@larryqiann this fix https://github.com/rustdesk/rustdesk/pull/4269 for #4261 may fix your problem.

**Comment by rivalcomp** [comment]
> @rivalcomp tell us more about your monitors plese, resolution and zoom factor etc.

On client side there is many-many variations, no difference in behavior depending on resolution. There is also no difference in behavior using different zoom factors (adaptive or fixed scaling). The issue is the same on physical Windows machines and VMs.

I have a feeling that this is an issue on slower client side machines (I can't tell you what/why/what CPU/what clock speed/what core count/etc., and it might be that it's not relevant, I have to test it further to be sure).

In opposite for example, on my own Windows 11 desktop there is no problem locally (Win 11, Ryzen, nVidia), so 1.2.0 -> 1.2.0 is working properly. Another strange feeling that the clients I connect to (and where the problem is an issue) have Intel based IGPUs, but I have to test is further too. On my VMs that also has this problem I'm using VBox's own drivers, and they are on localhost.

So all in all, I have many many more clients with this problem than without it. I can say 10% doesn't have this issue while 90% does. I have to revert back to 1.1.9 nearly everywhere to be able to do my job.

**Comment by rustdesk** [comment]
That's why we have no confidence to release 1.20 officially.

**Comment by fufesou** [comment]
> I have a feeling that this is an issue on slower client side machines

Maybe it's the reason.

https://github.com/rustdesk/rustdesk/blob/0ed209b4d2457642b0067ad6f0522fd46ddfe052/src/server/input_service.rs#L711

BTW, did you have RustDesk installed? Or just run a portable process and have elevated privileges?

**Comment by rivalcomp** [comment]
> BTW, did you have RustDesk installed? Or just run a portable process and have elevated privileges?

I'm using portable clients with elevated privileges everywhere.

**Comment by rustdesk** [comment]
> I'm using portable clients with elevated privileges everywhere.

Just curious, 1.1.9 can not elevate portable client, do you install or not install when you use 1.1.9?

**Comment by fufesou** [comment]
I've reproduced this issue.
I'll try to find the reason.

**Comment by rivalcomp** [comment]
> Just curious, 1.1.9 can not elevate portable client, do you install or not install when you use 1.1.9?

I run portable 1.1.9 with elevated privileges using right click context, or by enabling elevated privileges under properties - compatibility mode.

**Comment by rustdesk** [comment]
> I run portable 1.1.9 with elevated privileges using right click context, or by enabling elevated privileges under properties - compatibility mode.

You are advanced user, I even do not know using in this way.

**Comment by rustdesk** [comment]
@21pages is following up this portable elevated run issue.

**Comment by rivalcomp** [comment]
> The logic is updated yestoday. It will retry up to 100 micro-seconds now. Can you please try the latest build? Thx

Using the latest nightly (05.05.23 I guess?) as a client, it feels definitely better, but sadly it's far from usable (for me). It also has the same problems, but a bit less amount than before. (Of course it is just from a few minute quick test on my VMs, nothing more).

I definitely can say that under 1.1.9 I don't have to care about the mouse position, I always get the expected behavior when clicking. Using 1.2.0 as a Windows client I always have to make sure that the mouse is at the right place before clicking (or releasing the click). It's strange that 1.2.0 client is usable on a slow Linux Mint VM.

**Comment by rustdesk** [comment]
> I'm using portable clients with elevated privileges everywhere.

This is the cause, @21pages  is following up this.

**Comment by rivalcomp** [comment]
You just gave me an idea, and I've just discovered that an **unelevated** 1.2.0 doesn't have this mouse issue. Wow... :o
I always use elevated clients because unelevated clients are unusable for me. You can't click on anything after opening the Task manager or Device manager for example.

**Comment by rustdesk** [comment]
Installed version does not have these issues.

**Comment by fufesou** [comment]
It is Ok when elevating privileges through the client.
But there's something wrong if run as admin on the host, it's hard to control the mouse.

I'll find the reason.

**Comment by rivalcomp** [comment]
> It is Ok when elevating privileges through the client. But there's something wrong if run as admin on the host, it's hard to control the mouse.

On host side (the controller side) I never use it with privileged access because nothing requires it. I run privileged on the client (controlled) side only.

**Comment by rustdesk** [comment]
fufesou's client is your host. You have different view angle.

**Comment by larryqiann** [comment]
As of last evening, I have tested the latest nightlies and there is a noticeable improvement in smoothness. However, this test was done locally, so I still need to confirm whether it continues to be a problem over the network.

Something that my be somewhat related is that at least on mobile Android clients, it seems that the use of software decoding likely does put a large amount of stress on the CPU - for a 4K stream, it causes the processor of the phone to overheat and crash the app in just a few seconds. However, during this time, the mouse appears to function fine.

**Comment by rustdesk** [comment]
Close as PR #4278 #4261
