### ISSUE TITLE
Make it possible to disable showing the Installation window

### ISSUE THREAD

**Issue by A-7666** [rustdesk/rustdesk#382]
When running without installation (say portable mode, which is currently pseudo-portable), there's always this Installation window, which gets very annoying at some point. Would be great to just run the program, without seeing this window.

**Comment by rustdesk** [comment]
There are two downloads, the other one has no installation window.

**Comment by Agych** [comment]
Hello,

There are still 2 issues:

- In the main window, there is a message saying "Due to UAC... click to install to the system", without the opportunity to hide it. I also tried to run the EXE as administrator - didn't help, the message is still there.
Could an opportunity to hide it be added?

- The portable mode is still not actually portable, as it creates files in AppData instead of creating them in the same place where the EXE is located. Could this be fixed for the portable version?
