### ISSUE TITLE
macOS URL handler weird behaviour

### ISSUE THREAD

**Issue by SupersonicWaffle** [rustdesk/rustdesk#4069]
### Bug Description

When opening a URL like rustdesk://connection/new/xxxxxxxxx, it only works to open a new connection when RustDesk is closed.
If RustDesk is already running it will just activate the window.

### How to Reproduce

Use rustdesk:// URL when RustDesk is running

### Expected Behavior

Open a new connection as it does on windows

### Operating system(s) on local side and remote side

macOS -> any

### RustDesk Version(s) on local side and remote side

1.2.0 -> any

### Screenshots

none

**Comment by rustdesk** [comment]
@kingtous

**Comment by Kingtous** [comment]
Sorry for being late due to being quite busy these days. I've tested the latest macOS nightly build but I cannot reproduce your problem, I can open a new connection via `rustdesk:://` schema, no matter whether the RustDesk window is running or not.

Please make sure u are using the latest macOS nightly build from our repo, and install the .app into your `Application` folder.

If the problem still exists, please provide the log from your terminal by opening RustDesk with this command:

```
/Applications/RustDesk.app/Contents/MacOS/RustDesk
```

an example of the log after your invoke your schema:

```
flutter: uni links called:
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: [0]
```

and a more question: have you installed the service by clicking the installation button and entering your password?

**Comment by rustdesk** [comment]
I have confirmed, it works when service is both installed and not installed. 

@Kingtous but I see another issue, when service is installed and the main window (or connection windows) is not active, it can not activated by clicking on RustDesk icon in lauchpad, please take a look.
