### ISSUE TITLE
German translation for keyboard Map mode is misleading

### ISSUE THREAD

**Issue by pavel-krivanek** [rustdesk/rustdesk#4125]
### Bug Description

The German translation for 'Map mode' used in RustDesk, 'Kartenmodus', is misleading because this term is strongly cartography related. Die Karte is a map, but this word is mostly used only for plans. 

Instead of 'Kartenmodus' translation should be 'Zuordnungsmodus' or just 'Zuordnung', better: 'Zuordnung extern'

### How to Reproduce

-

### Expected Behavior

-

### Operating system(s) on local side and remote side

Windows 10

### RustDesk Version(s) on local side and remote side

1.2.0 nightly

### Screenshots

-

**Comment by rustdesk** [comment]
@grummbeer

**Comment by rustdesk** [comment]
@Mr-Update

**Comment by rustdesk** [comment]
I have checked google translate, `Zuordnungsmodus` is better, @pavel-krivanek could you submit a PR to fix it?

**Comment by grummbeer** [comment]
just for the record … some time ago I made the following note to my personal "todos".

### 1. context

The context for translators is missing. It is hard to know where in the UI the "map mode" is used. But knowing where it is visible is necessary to make the right translation.

### 2. neutral naming

- Legacy mode
- Map mode
- Translate mode

For "en" this is OK. But become a riddle for translators.

"X mode" refers to a technical thing, in this case something to the keyboard. Trying to describe a technical process in one word is a bit difficult. Translators need to know what the "X Mode" stands for to make a proper translation.

Even with more context, e.g. `"toolbar.keyboard.mode.map_mode": "map mode"`, the tranlator try to find a good translation but fail because it's not clear what a "map mode" is.

So the question is: Is it relevant to the user what tech is used? If not, translators should not try to translate a technical thing if it is not necessary.

The options could simply called (tech neutral) 

- "Keyboard mode 1"
- "Keyboard mode 2"
- "Keyboard mode 3"

or 

- "Darth Vader mode"
- "Indiana Jones mode"
- "Mickey Mouse mode"

It's all the same, it's important to find the right mode easily (rememberable) and not what the underlying technology is.

**Comment by rustdesk** [comment]
> `"toolbar.keyboard.mode.map_mode": "map mode"`,

totally agree
