### ISSUE TITLE
Flyout (float menubar on remote connection window) (Settings) position and behaviour

### ISSUE THREAD

**Issue by FCrane** [rustdesk/rustdesk#4358]
### Bug Description

Hi!

A few issues with the  settings flyout (is it called that?):

1) The position can not be set close to the left and right edge of the Rustdesk window. If I try to e.g. move it to the far right, it moves back within the center third of the window. It should be possible to place it anywhere I want (so that it does not obscure important info on the remote machine).

2) When I click the arrow to show the full settings flyout, it always appears centered on screen, not where the arrow box is (see screenshot). It should appear under the arrow.

3) The position of the box is not remembered between sessions. When I move it somewhere, I'd like to have it at exactly this position the next time I open the connection.

Regards!

### How to Reproduce

See description

### Expected Behavior

See description

### Operating system(s) on local side and remote side

Windows 11 x64

### RustDesk Version(s) on local side and remote side

Latest nightly

### Screenshots

![Flyout](https://github.com/rustdesk/rustdesk/assets/14123400/de8cafdd-1f30-4c91-b2c0-defe6783c0ca)

**Comment by rustdesk** [comment]
@fufesou totally agree, let's do job more elaborate.

**Comment by fufesou** [comment]
@FCrane Thanks for your feedback.

1. The menu bar always show on the center may not be the problem. When it shows, you may need some operations on the menu or settings. Rarely do you need to modify the settings and see the section hidden by the menu.
2. The arrow box is draggable because it cannot be hidden.  It should not be far away the menu. Otherwise it looks weird.
3. The position of the arrow box can be remembered. I'll do it later.


https://github.com/rustdesk/rustdesk/assets/13586388/4286c26b-2416-427e-992a-b0e4cb176aff

**Comment by FCrane** [comment]
Hi!

Yes, the menu bar showing in the center is not a problem, because it's used rarely. However, the arrow box is blocking some important parts of the desktop in my configuration. AND: I can not move the arrow box to the left or right side of the RustDesk window (like in your video)! It always jumps back to the middle third of the window! I need it further to the left or right side and its position should be remembered between sessions.

Thanks!

**Comment by rustdesk** [comment]
close as fix merged
