### ISSUE TITLE
Does it plan to support socks5 proxy in future ?

### ISSUE THREAD

**Issue by zxyqq** [rustdesk/rustdesk#46]
Does it plan to support socks5 proxy in future ?

**Comment by rustdesk** [comment]
no plan yet

**Comment by rustdesk** [comment]
@zhangxianyi could u let me know why do u need socks5 proxy？i know tv etc have this. i wanna understand your scenario better.

**Comment by kvn95ss** [comment]
Not the poster but some universities / institutes use socks5 proxy, maybe thats why?

**Comment by zhangxianyi** [comment]
Thanks for your kind reply!
  Because my computer in company  can not connect to the internet directly. while some another computer in the company can. 
  So I have configured socks5 proxy between them. Currently I am writing this reply by the proxy.
  I will be very appreciated, if you can add the socks5 proxy feature!

**Comment by rustdesk** [comment]
https://docs.rs/tor-stream/0.3.0/tor_stream/

**Comment by rustdesk** [comment]
https://crates.io/crates/proxychain

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/6d506cbb649ab60e9e978ebfab8b4d16043a4252

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/pull/353

**Comment by mcarbonneaux** [comment]
> > no plan yet
> 
>     * 1 for https_proxy, ,to  be useful in corporate environments,  plz. I can support $50 for a bounty for  this feature.

the support for proxy https (CONNECT tunneling) permit tu use rustdesk in enterprise environement, who generaly are not directly connected to internet... and not permit generaly sock proxy...
