### ISSUE TITLE
Rustdesk always creates an autostart entry

### ISSUE THREAD

**Issue by jkhsjdhjs** [rustdesk/rustdesk#4863]
### Bug Description

Rustdesk always creates an autostart entry with no option to disable this behavior:
https://github.com/rustdesk/rustdesk/blob/06af880b126f462591bfcf06c29995c86d3c1852/src/platform/linux.rs#L1179-L1198

Furthermore, if `$HOME` isn't set, this attempts to create an autostart entry in `/.config/autostart`.

### How to Reproduce

Start rustdesk.

### Expected Behavior

Don't create an autostart entry automatically.

### Operating system(s) on local side and remote side

Arch Linux

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

Screenshots shouldn't be required.

**Comment by jkhsjdhjs** [comment]
You can't be serious.

**Comment by irminsul** [comment]
If all you have is a hammer...

```shell
truncate -s 0 ~/.config/autostart/rustdesk.desktop
sudo chattr +i ~/.config/autostart/rustdesk.desktop
```

**Comment by OboTheHobo** [comment]
This is absolutely ridiculous. Forcing autostart and automatically _undoing the user's attempt to undo it?_ I'm removing rustdesk entirely because of this. Unfathomably stupid. It's stupid enough to not give an option for the user to remove autostart easily from within the app, but attempting to stop the user from changing this from outside is just blatantly anti-user. In fact, it makes me suspicious of the app entirely that it wants to badly to always be running even against the intentions of the user... if it wasn't for the fact that the project was open-source, I would assume it's malware. Anyone outside the project inspected the source code enough to be sure it isn't?

**Comment by ekasprzak** [comment]
@rustdesk would you be so kind to provide any explanation why this is wontfix?

I believe this is a valid point for use cases when only on-demand remote connection is needed (meaning asking a person using the destination machine to run the app first).

**Comment by md-owes** [comment]
@ekasprzak, @rustdesk is not even kind enough to respond you. BTW, it still auto starts itself upon restart on Ubuntu 24.04.

**Comment by Mohammad699** [comment]
@rustdesk this is very very suspicious behavior, why you won't fix and why you don't answer?!

**Comment by Flummi** [comment]
where fix, wtf

**Comment by licentiapoetica** [comment]
this is unbelievable actually.

why is this being ignored and not properly addressed? @rustdesk

**Comment by LemiSt24** [comment]
marked as "wontfix"...

I guess I won't ever be using rustdesk anymore.

**Comment by rustdesk** [comment]
fixed in https://github.com/rustdesk/rustdesk/commit/421ddc001603b014a45d8492894989816e4e6f66

**Comment by ekasprzak** [comment]
Awesome, thank you @rustdesk !
Is there going to be a setting that allows to enable/disable the autostart or it's just disabled completely?

**Comment by basilgello** [comment]
@rustdesk If you decide to make autostart entry creation configurable (you probably should), can you please make `crate::common::check_software_update()`, `crate::common::test_nat_type()`, and `crate::common::test_rendezvous_server()` configurable too?

One setting would be "Do not check NAT on application start", default false (for nat + rendezvous tests)
Another would be "Do not check new releases", default also false (for doftware update)

This allows us to remove Tracking AntiFeature on F-Droid - something that I promised to do back in November :)

**Comment by md-owes** [comment]
We do not want to sound demanding or demeaning the developer of such a fantastic piece of software provided to us for free, it is just that we are so accustomed or dependent on this software that it becomes hard for us to compromise on a bug that is so annoying that we either start thinking of uninstalling or moving to alternatives. In both cases, it is a loss for both the developer and the consumer. Thank you @rustdesk for fixing it and please try to respond to queries in order to calm things down. We really appreciate your efforts for providing this amazing software for free and request you to be little more active in the issues section.
