### ISSUE TITLE
来个群晖的套件？

### ISSUE THREAD

**Issue by MeowCold** [rustdesk/rustdesk#5]
来个群晖的套件？

**Comment by zhangbo8418** [comment]
控制端要这个有啥用？我做了个服务端的群晖套件。。。http://bobohome.f3322.net:8880/sspks/

**Comment by rustdesk** [comment]
啥意思2020年12月22日 15:51，MeowCold <notifications@github.com>写道：

来个群晖的套件？

**Comment by MeowCold** [comment]
@zhangbo8418 233 你居然都已经全机型适配了 好厉害

**Comment by zhangbo8418** [comment]
> 啥意思2020年12月22日 15:51，MeowCold <notifications@github.com>写道： 来个群晖的套件？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，啥时候能支持Windows2008R2 Windows2019？还有那个手机端能不能加入手势啊。。。现在太难用了，比方双指轻击右键，双指上下滑动，单指双击不放拖动之类等？

**Comment by rustdesk** [comment]
这些手势都有，你需要点击下面鼠标按钮，然后顶部就有几种模式让你选，scroll就是滚动轴模式相，drag就是拖动，right就是右击，之前考虑过通过touch数自动切换模式，但是实际使用也没那么方便2020年12月22日 20:10，裙下孤魂 <notifications@github.com>写道：



啥意思2020年12月22日 15:51，MeowCold notifications@github.com写道： 来个群晖的套件？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.



大佬，啥时候能支持Windows2008R2 Windows2019？还有那个手机端能不能加入手势啊。。。现在太难用了，比方双指轻击右键，双指上下滑动，单指双击不放拖动之类等？

**Comment by rustdesk** [comment]
server暂时不考虑 又没人付钱 开发了也没意义2020年12月22日 20:24，info@rustdesk.com写道：这些手势都有，你需要点击下面鼠标按钮，然后顶部就有几种模式让你选，scroll就是滚动轴模式相，drag就是拖动，right就是右击，之前考虑过通过touch数自动切换模式，但是实际使用也没那么方便2020年12月22日 20:10，裙下孤魂 <notifications@github.com>写道：



啥意思2020年12月22日 15:51，MeowCold notifications@github.com写道： 来个群晖的套件？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.



大佬，啥时候能支持Windows2008R2 Windows2019？还有那个手机端能不能加入手势啊。。。现在太难用了，比方双指轻击右键，双指上下滑动，单指双击不放拖动之类等？

**Comment by zhangbo8418** [comment]
> 这些手势都有，你需要点击下面鼠标按钮，然后顶部就有几种模式让你选，scroll就是滚动轴模式相，drag就是拖动，right就是右击，之前考虑过通过touch数自动切换模式，但是实际使用也没那么方便2020年12月22日 20:10，裙下孤魂 <notifications@github.com>写道： 啥意思2020年12月22日 15:51，MeowCold notifications@github.com写道： 来个群晖的套件？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 大佬，啥时候能支持Windows2008R2 Windows2019？还有那个手机端能不能加入手势啊。。。现在太难用了，比方双指轻击右键，双指上下滑动，单指双击不放拖动之类等？ —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

我的意思是这玩意儿还需要点。。。。
