### ISSUE TITLE
Trackpad Scrolling/Zooming fail for Rust Client 1.2.0-1.2.2

### ISSUE THREAD

**Issue by joecklau** [rustdesk/rustdesk#5500]
### Bug Description

Tested with Rust Client 1.1.9, 1.2.0, 1.2.2, 1.2.3 (nightly build)
Trackpad Scrolling and Zooming was working well previously; but failing on/after 1.2.0 until 1.2.2 (and 1.2.3 nightly build)
Tested OS: Windows 11

### How to Reproduce

Try scrolling/zooming on any screen, e.g. browser. It worked on/before 1.1.9; but failing on/after 1.2.0

### Expected Behavior

Scrolling/Zooming should work like 1.1.9/before

### Operating system(s) on local side and remote side

Windows 11

### RustDesk Version(s) on local side and remote side

1.2.2

### Screenshots

Screenshot is meaningless in this case.

**Comment by rustdesk** [comment]
@fufesou again?

**Comment by rustdesk** [comment]
Wokring well in my test.

**Comment by fufesou** [comment]
Trackpad Scrolling/Zooming also work in my test. The controlled side is Windows.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367, and mark as unreproducible

**Comment by rustdesk** [comment]
Zoom on controlled mac + linux is not supported yet.

**Comment by joecklau** [comment]
Can't believe it can be closed so fast within half hour, without real check.
It's easy to re-produce the scenario. See how I compare v1.2.2 vs 1.1.9 with this fresh-recorded video
https://youtube.com/shorts/fW1fGnrEdyg?feature=share

**Comment by rustdesk** [comment]
Make sure controlled side is not 1.1.9.

BTW, it is not simply closed, it is tracked by #4367.

**Comment by joecklau** [comment]
Oh you're right! The controlled side was installed with v1.1.9 and the controller is v1.2.x when the issue happened.
After I replace the controlled side with v1.2.2, it can be scrolled and zoomed normally.
Thanks!

**Comment by rustdesk** [comment]
Next time, be clever please before creating issue on anyone's repo.

**Comment by rustdesk** [comment]
> ### RustDesk Version(s) on local side and remote side

Also pay attention something like this.

**Comment by tohizma** [comment]
Related with trackpad / touchpad, perhaps I'm not hijacking this thread

Host version: 1.2.3 Build date: 2023-10-11 10:04
Client version: 1.2.3 Build date: 2023-10-11 10:04

Tried on Lenovo X1 Laptop

Two finger gesture which is assumed as scroll works well for scrolling page (web page for example) which only have vertical scroll bar, but when using apps with vertical and horizontal scroll bar (visual studio code/notepad++) when try to scroll vertically will be shaky, it will scrolls to left and right too at random degree

Expected behavior: should be scroll vertically when gesture up or down and scroll horizontally when gesture move left or right
