### ISSUE TITLE
Monterey upgrade issues, possibly due to OCLP?

### ISSUE THREAD

**Issue by jd544089** [rustdesk/rustdesk#5503]
### Bug Description

Was using the program just fine on Catalina but upgraded an older system due to lack of OS support. Installed OpenCore Legacy patcher and upgraded to Monterey. On it's first launch after install, the dock doesn't seem to want to make space for the icon, but then it loads and gives a black window screen, nothing in it and no ability to click on anything save tile or close buttons.

I have reinstalled RD several times without any changes, hoping this was just an updated OS issue and something got stuck in the upgrade. I have deleted all plists and everything I could find, rebooted, reinstalled. I've done this 4 times and I still get a black window.
 
I have no problems on any other devices, even VMWare installs, and this is the only system I've used OCLP on. When I force quit the app, it seems to hang and finally goes away, after the dock acting odd for a few seconds.

I have left the app open for several hours and there are no changes until I force quit RustDesk. Sometimes I reboot the machine due to the icon bugginess worrying me.

### How to Reproduce

Launching the app it will always give the black/blank window screen.

### Expected Behavior

After the upgraded OS, I expected to be able to use the app as normal. Now that I've uninstalled it I don't even have the option to use RD from other computers into this one.

Currently, I expect it to launch and start asking for permissions and other add-ins it needs to properly work.

### Operating system(s) on local side and remote side

macOS Monterey

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

![RustDesk Screen Shot 2023-08-24 at 11 26 44 AM](https://github.com/rustdesk/rustdesk/assets/143121861/415e60e6-509f-42ed-847f-c3f74c049686)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/4357#issuecomment-1601808533

**Comment by willmcginnis** [comment]
I'm not a dev on rustdesk but the logic of linking this to VMware compatibility is the thing that VMware and opencore legacy patcher have in common is the hardware isn't regular hardware, but there are software tricks being done.

I would like to run rustdesk in a MacOS VM myself and the lack of metal support without using one of the hackintosh kexts or kext patching to enable metal support is likely the fix for me, and probably would work here too.

Also running from a terminal and getting a log is always helpful. If you're new, you get a log from running an application on macos by running the executable inside the .app bundle. For example, for rustdesk in the /Applications folder, see this screenshot:

https://github.com/rustdesk/rustdesk/issues/4357#issuecomment-1601808533

**Comment by jd544089** [comment]
VMware Fusion is another app I am having trouble with (pipeline -14 error). 

The way you put it, it sounds like it's almost a computer running a VM version of Monterey and within that another VM -- be it VMW or RD.  I am using janky VirtualBox and TVeamViewer without issue, which blows my mind.

TY for adding your comment. It's a long process and so many reinstalls that I'm glad it's the weekend and I can try some. With OCLP, there's so many "switches to flip" that I've no idea which, if any, SIP or SMBIOS settings could fix things or make things worse.

I am about to install RD 1.2.1 that I remember worked on this setup before OCLP. Maybe I'll have to run a few logs (if I do it right!) Thank you.
