### ISSUE TITLE
Input (WSL) has stopped working on Win11 from Debian buster on crosvm

### ISSUE THREAD

**Issue by macccorehenni** [rustdesk/rustdesk#5519]
### Bug Description

I'm trying to help my father with learning Linux using WSL. However, the remote end does not accept any input in any of the three modes.

### How to Reproduce

* Open a connection to the Windows 11 computer on Debian.
* Attempt to input words
* Fails to register on Windows 11

### Expected Behavior

The text should show up

### Operating system(s) on local side and remote side

Debian bullseye on Crostini -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.1->1.2.1

### Screenshots

[c252978891_20230826091705_VP9.webm](https://github.com/rustdesk/rustdesk/assets/93945758/2288d555-1fee-4128-9f8c-74fdbc3992eb)

### Additional Context

On the Win11 side, there had been issues with the internet. We tried restarting several times on both ends. It worked wonders last night, but his issues started today. It might be beacuse of internet issues, but I wanted to see if anyone else was having this issue.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3977

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@macccorehenni Hi, thanks for your feedback.

I've tried Debian 12 PC --> Win 11, both the latest ngihtly build. Both X11 and Wayland on the local side are tested.
I open a WSL terminal, the input works fine.

But I can't test and support crosvm, because I don't have a ChromeBook. Sorry for that. @rustdesk @macccorehenni 

BTW, can you please check if the input works with the Win11 notepad? Is the mouse input work?

**Comment by rustdesk** [comment]
So this issue is in the same case as https://github.com/rustdesk/rustdesk/issues/3977

**Comment by rustdesk** [comment]
Close this to favor #3099

**Comment by rustdesk** [comment]
@macccorehenni if possible, can you let @fufesou connect to you machine for testing?
