### ISSUE TITLE
Connection window not closed after clicking "disconnect" button in 1.1.9

### ISSUE THREAD

**Issue by wanghu572** [rustdesk/rustdesk#553]
RT

**Comment by UPEngineer** [comment]
I am having the same issue. When I click the Disconnect button, sometimes the disconnect window closes and sometimes it does not. However, either way, the connection to the remote computer still persists.

Windows 1,1.9 64-bit. Downloaded just a few minutes ago.

**Comment by rustdesk** [comment]
> Disconnect

Really, I just repeatly tested, it worked fine. @wanghu572 do you still have the problem?

**Comment by UPEngineer** [comment]
Yes. I have done some more testing and found that on two different remote computers, the box that pops up after connecting that has the Disconnect button will disappear after a few seconds. I have not figured out a way to get that box back. If I click the Disconnect button when it is visible, it does nothing. I thought originially that the box disappeared after clicking the disconnect button, but I think it just coincided with the disappearance of the box mentioned above.

The only way I can disconnect a remote session is to click the X on the upper right corner. 

I will try to connect from another computer to see if the issue is on this computer or not.

**Comment by rustdesk** [comment]
Make sure your background RustDesk service is updated.

**Comment by UPEngineer** [comment]
Shows RustDesk service is running. Is that what you mean, or is there something else I need to look at? And that is on the host computer too, right?

**Comment by rustdesk** [comment]
You need to updated RustDesk on the controlled side, including the RustDesk background service on the controlled side (reinstall RustDesk).

**Comment by grummbeer** [comment]
@UPEngineer can this be closed?

**Comment by UPEngineer** [comment]
> @UPEngineer can this be closed?

Yes.
