### ISSUE TITLE
Rustdesk can't remote control wayland host

### ISSUE THREAD

**Issue by FurtadoPires** [rustdesk/rustdesk#5949]
### Bug Description

Rustdesk remote control is not working when the host is running a wayland session. Despite allowing remote control at the connection, the controller side can only see the image of the host machine, but without being allowed to use keyboard or mouse.

The distro I've tested is Manjaro running GNOME, so I don't know if other Distros / Desktop Environments have the same problem. I've tried "Windows -> Manjaro" and "Manjaro -> Manjaro", using rustdesk from source and flatpak, and in all cases I couldn't send mouse and keyboard inputs to the wayland host.

Remote control "Manjaro -> Windows" works as expected.

Specs:
-Rustdesk v1.2.3
-Kernel 6.5.5-1
-Distro: Manjaro x64
-Wayland 1.22.0-1
-Desktop Environment: GNOME 44.5
-Compositor: Mutter 44.5-1
-Flatpak v1:1.15.4-1

### How to Reproduce

-Install rustdesk
-Login in a wayland session
-Allow another client to connect to your session

### Expected Behavior

-The remote connection should be able to control your mouse and keyboard

### Operating system(s) on local side and remote side

Windows 11 -> Linux, Linux -> Linux

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

![rustdesk 123](https://github.com/rustdesk/rustdesk/assets/7890832/1554ebbc-b057-46eb-aa3a-82e29497ad8f)

### Additional Context

[Flatpak officially supports input capture through portal](https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.18.0) so It shouldn't be a problem in this case.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by FurtadoPires** [comment]
Just an observation that it affects source installation (not just flatpak). Haven't asked about appimage, since appimage itself doesn't support wayland.

**Comment by sahilyeole** [comment]
>[Flatpak officially supports input capture through portal](https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.18.0) so It shouldn't be a problem in this case.

>Just an observation that it affects source installation (not just flatpak).

The thing is even if flatpak supports input capture from remote we are using `uinput` for emulating input key presses/mouse on wayland and `uinput` requires sudo privilege (in order to access dev/uinput).
On normal installation the rustdesk --service has to be started as root for input emulation.
So to fix this issue we need permission to access to dev/uinput for the flatpak version of rustdesk.
https://github.com/rustdesk/rustdesk/issues/2798#issuecomment-1413028783

**Comment by rustdesk** [comment]
You do not have to use uinput, there is flatpak feature. You can write your logic in flatpak.

**Comment by sahilyeole** [comment]
>The InputCapture portal merely *manages* the logic when input should be captured. The transport of actual input events is delegated to a transport layer, specifically libei.

https://flatpak.github.io/xdg-desktop-portal/docs/#gdbus-org.freedesktop.portal.InputCapture

The feature can only transfer input from remote to linux but it cannot emulate input on linux on its own. For emulating it requires [libei](https://gitlab.freedesktop.org/libinput/libei) which might require its own separate implementation, different from what we are already using for wayland.
I will give it a try but first I'm trying privilege elevation in order to use uinput for flatpak.
