### ISSUE TITLE
Security concerns have been taken to Github

### ISSUE THREAD

**Issue by alecgm** [rustdesk/rustdesk#62]
I am writing because it seems that security related questions have been intentionally deleted time and time again by the anonymous rustdesk author. 

Also I've heard that the security concerns have been taken to Github to look into this behaviour because it was suggested that parts of Rustdesk might be intentionally malicious.

So I would hereby like to ask the author, please state why you would do this. Apps as powerful as rustdesk must hold up to these kind of scrutiny.

Therefore I want to know in the name the community what's going on here.

**Comment by rustdesk** [comment]
So you register a new GITHUB account. I did delete two issues, because they (I do not know which one is you, both are good businessman) had been asking me open source the server code, it was really annoying.  As a response, I wrote https://github.com/rustdesk/rustdesk-server-demo. Regarding whether RustDesk is intentionally malicious, the community can help you.
