### ISSUE TITLE
FDroid Version Very Old

### ISSUE THREAD

**Issue by SPDurkee** [rustdesk/rustdesk#6409]
### Bug Description

FDroid has v1.1.10-1. Please update the version on FDroid or remove it from the readme

### How to Reproduce

View RustDesk on FDroid

### Expected Behavior

V1.2.3

### Operating system(s) on local side and remote side

Android

### RustDesk Version(s) on local side and remote side

NA

### Screenshots

NA

**Comment by basilgello** [comment]
1.2.3 was built and after Ciaran signs the latest F-Droid batch, it will become available to general public.

**Comment by basilgello** [comment]
F-Droid index updated, download available!

**Comment by beeb** [comment]
Can we get a new update on f-droid? It's been a while

**Comment by basilgello** [comment]
The 1.2.6 build was merged into index but actual builds made tonight habe failed and I need to investigate with the F-Droid team why production buildserver failed to build stuff that was built fine using their CI system.

On top of that, all previous Rustdesk versions older than 1.2.6 will be pulled off F-Droid due to https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15343#note_1996539204

I am really doing my best fighting the uphill battle but at best, 1.2.6 will be delayed to 3-5 more days.

**Comment by basilgello** [comment]
@rustdesk FYI ^^

**Comment by beeb** [comment]
Thanks for the update @basilgello . I tried to update my f-droid install with the APK downloaded from the releases page on here but it failed saying the "package appears to be invalid". So maybe that's related to the failure over at F-Droid.

**Comment by basilgello** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/2278d948ac960b94d70f1b6fcab5b90121255015 merged. Unfortunately we have towait for next build cycle and x86 architecture is removed because of the discussion linked above :(

**Comment by basilgello** [comment]
1.2.6 available on F-Droid. The fixup enabling full hardware codec support is awaiting for merge: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15386
