### ISSUE TITLE
Share image in clipboard

### ISSUE THREAD

**Issue by caoli5288** [rustdesk/rustdesk#683]
Please add this support, THX

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/rustdesk) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/rustdesk/rustdesk/issues/683">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/rustdesk/rustdesk/issues/683/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/rustdesk/rustdesk/issues/683/pledge.svg">
</picture>
</a>

**Comment by harris2310** [comment]
Hello there, I could resolve this for you

**Comment by caoli5288** [comment]
> Hello there, I could resolve this for you

@harris2310 How to?

**Comment by harris2310** [comment]
I'll do some research on it

**Comment by congzhangzh** [comment]
How about remote file copy like rdp?

**Comment by GermMC** [comment]
> Hello there, I could resolve this for you

 waiting~

**Comment by harris2310** [comment]
I recently start working on a new job so I won't be able to ,
Sorry for the late reply

**Comment by aoozoo** [comment]
It's too bad mstsc yyds

**Comment by brtwrst** [comment]
Any news on this? The ability to copy paste screenshots between systems via the clipboard would be very helpful.

**Comment by vraicovi** [comment]
I'll comment here just so this bubbles up to the top.  I could have sworn this functionality was there at some point, but I might be mashing together memories with TeamViewer.  This would be an amazing feature to add.

**Comment by rustdesk** [comment]
This is a good example of how to get your feature request higher priority.

https://twitter.com/rustdesk/status/1770643072118095914

**Comment by unholyHub** [comment]
> Any news on this? The ability to copy paste screenshots between systems via the clipboard would be very helpful.

Still not working on current version...

Version: 1.2.3-2
Build date: 2024-04-07 08:56

Also good feature to be when switch to another language different than English, key shortcuts are blocked and not working.

**Comment by gao-xiangyang** [comment]
如果支持windows与windows系统之间支持图元信息的COPY，需要在GetClipboardData针对几种format格式进行特殊处理，因为直接通过GetClipboardData获取的HANDLE并不是一个globlemem(`libs\clipboard\src\windows\wf_cliprdr.c:2591`)，它在这几种format类型中分别对应一个结构体指针：
CF_BITMAP->HBITMAP
CF_ENHMETAFILE->HENHMETAFILE
CF_METAFILEPICT->LPMETAFILEPICT

你应该完整的获取对应的图元信息后发送给peer。@rustdesk

我是一个C++\QT开发，对于rust编程是0基础，我正在尝试搭建调试环境...如果调试环境搭建成功，我会尝试pr。

**Comment by rustdesk** [comment]
ready in nightly build https://x.com/rustdesk/status/1807981430775206289

**Comment by rustdesk** [comment]
@gao-xiangyang Thanks, we have done this with arboard crate which helps us doing format conversion for different OS. But there is an issue with SVG.

**Comment by gao-xiangyang** [comment]
Alright, I saw the fork (fix/win_clipboard_image) by fufesou, and it seems like he has resolved the issue with copying images. However, I believe this only addresses the surface problem, as there are other hidden issues within the entire clipboard process. Due to architectural flow problems, I think these issues will eventually surface.

For example: In my local system's PowerPoint software, I selected some shapes and a slide. Currently, I am unable to paste from the remote system because not all clipboard formats supported locally are synchronized. In the current release version, I only see the text format. You can use `FreeClipViewer.exe` to separately view the clipboard contents of the remote system and the local system.

Such problems will become more frequent: For instance, if Photoshop supports clipboard formats with layers, allowing you to copy from one Photoshop window to another, it would still fail to copy in RustDesk's remote clipboard.

What I want to illustrate is that when both ends of the system are the same, there is no need to convert the clipboard content data. We can simply send the original clipboard content directly. RustDesk does not need to be concerned about the clipboard format. Since both systems recognize their own clipboard formats, only when dealing with cross-operating systems should we parse these clipboard contents and convert them into the corresponding clipboard format content.

I hope this can help improve future product solutions. @rustdesk

**Comment by rustdesk** [comment]
Thanks, there is alway big space  of improvement.
