### ISSUE TITLE
Web client not working

### ISSUE THREAD

**Issue by lc700x** [rustdesk/rustdesk#6867]
### Bug Description

I could not connect the remote desktop via web client (beta). It always shows connection error and timeout. 

### How to Reproduce

Open [RustDesk Web Client](http://45.76.181.120:8080/#/), and try to connect a remote ID. 

### Expected Behavior

Connection Error. Timeout.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.3 -> Web(Beta)

### Screenshots

![connect error](https://github.com/rustdesk/rustdesk/assets/34005574/fd109d93-f98f-4843-93c6-2f04d24cdde0)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/6851#issuecomment-1886795662

**Comment by TBG-FR** [comment]
@rustdesk I've seen your comments on issues related to web client 
> This web client is not maintained. Need to upgrade, but we have no resource yet.
  
> Web client is meta, not maintained for very long yet. No issue accpetable.

I understand your lack of resources, but I'm sure the community (including myself) would be glad to help build and maintain the web client in a good usable state, and it would be great for the whole RustDesk project, because there's no good alternatives that provide a web client...

Today, RustDesk docs provides good instructions on how to build and run the web client, but it's on an outdated fork (that comes with some issues)... However, the desktop and mobile clients are really good (and working well) !

Is the web client deployed on http://45.76.181.120:8080/#/ (previously web.rustdesk.com ) built with the "outdated" fork, or with the code of the `master` branch ? Do you have something closed source or is it still open source ? Anything else you have in mind ?

**Comment by TBG-FR** [comment]
Sorry to bother you but can you answer to that @rustdesk please ?

> @rustdesk I've seen your comments on issues related to web client
> 
> > This web client is not maintained. Need to upgrade, but we have no resource yet.
> 
> > Web client is meta, not maintained for very long yet. No issue accpetable.
> 
> I understand your lack of resources, but I'm sure the community (including myself) would be glad to help build and maintain the web client in a good usable state, and it would be great for the whole RustDesk project, because there's no good alternatives that provide a web client...
> 
> Today, RustDesk docs provides good instructions on how to build and run the web client, but it's on an outdated fork (that comes with some issues)... However, the desktop and mobile clients are really good (and working well) !
> 
> Is the web client deployed on http://45.76.181.120:8080/#/ (previously web.rustdesk.com ) built with the "outdated" fork, or with the code of the `master` branch ? Do you have something closed source or is it still open source ? Anything else you have in mind ?
