### ISSUE TITLE
AltGr Key has no effect

### ISSUE THREAD

**Issue by jameskitt616** [rustdesk/rustdesk#728]
**Describe the bug you encountered:**
When pressing `AltGr + q` -> @ or `AltGr + e` -> € etc., the remote does either print nothing or something wrong.

**What did you expect to happen instead?**
On the Remote machine it should print the input.
From Windows -> Ubuntu just nothing happened.
From Ubuntu -> Windows it printed `e` instead of `€` or `q` instead of `@`

**How did you install `RustDesk`?**
GitHub release

**RustDesk version and environment**
For Ubuntu 22.04 via deb package. (v.1.1.9)
For Windows the installed version (not portable). (v.1.1.9)

**Comment by jameskitt616** [comment]
I noticed it's not just those keys, the entire german keyboard layout is not getting translated correctly or keys dont get recognized at all when pressing them.

**Comment by aceofbitcoin** [comment]
When You plan to solve this bug for God sake.

**Comment by rustdesk** [comment]
try out nightly build please in github release page

**Comment by rustdesk** [comment]
#1547

**Comment by rustdesk** [comment]
dup: https://github.com/rustdesk/rustdesk/issues/2316

**Comment by hexbinoct** [comment]
want to ask, my right Ctrl for copy paste is not working, is it related? I am using left Ctrl keyboard button that works. thanks.

**Comment by fufesou** [comment]
> right Ctrl for copy paste is not working
@hexbinoct Try nightly build, with "Map mode".

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210552899-959f016f-fae8-45ec-bac5-9d84f7f2f060.png">

**Comment by blackandcold** [comment]
Right CTRL and ALT do not work at all.
In the German layout the CTRL-C/V do not work with the right CTRL but with the left one.

Also µ @ and € all set with right ALT key (AltGr) as well as ~ do not work because of this.
I could not find out why I can't type ~/.something or ssh user@123.123.123.123 until I realized it is Rustdesk.

If you need any keycodes or other support to solve this, please ask.

Source system is Windows 11 (latest) and target is EndeavourOS (latest obviously) both German locale and de layout settings.

**Comment by rustdesk** [comment]
#1547
