### ISSUE TITLE
Clipboard logic still broken. (multiple connections)

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk#7321]
### Bug Description

Client connected to host A and B.

Copy text on A -> Clipboard goes to Client. Ok.
Paste on B -> Client Clipboard is not yet present on B. (Ok, we don't want to broadcast on ctrl-c)

Paste it on Client, Select it again, Copy, Paste on B. -> Client Clipboard is still not present on B. <------ wrong

Paste on Client, Copy something else into the clipboard, Select original text, Copy, Paste on B. ->
Client Clipboard is now present on B.

There is a check in place to determine if the clipboard has changed, which is preventing the expected behavior.

### How to Reproduce

Same as above.

### Expected Behavior

Working clipboard

### Operating system(s) on local side and remote side

Windows 10 -> Windos 10*

### RustDesk Version(s) on local side and remote side

1.24 feb 28

### Screenshots

![jzanZCM](https://github.com/rustdesk/rustdesk/assets/17452773/541364c3-d8d5-4941-91d6-e5c2f6a19df0)

**Comment by attikov** [comment]
Since the clipboard transfer automation is heavily defective, it would be necessary to have an explicit button for sending and receiving the clipboard content. However, it should be easily accessible, at least with an option to toggle the presence of these buttons on or off, if you don't want to alter the standard appearance.

**Comment by jasonmacer** [comment]
I can confirm this, but I think I see where the issue is.
There is something stopping the clipboard from allowing to transfer to existing sessions. 

Here is what I just tested:

Local (Win10)
Remote A (WinServer2k22)
Remote B (Win10)
Remote C (Win11)
Remote D (WinServer2k19)

If I have Remote A & Remote B open and I copy something from A, it is not pastable to B.

I can paste it to Local. I cannot paste to local then copy that same information and paste to B. 

I can paste to local THEN select something else and paste to A or B.

I can copy something from A or B THEN open a connection to Remote C and I can paste from A or B to C, but not from A to B or B to A.

I CAN copy from A, B, or C then paste to local THEN select and copy something different then go back and select the original content and I can paste to to all the existing other connections.

Looks like I am running Version 1.2.3-2 on all machines.

Thanks guys! I love this!

**Comment by attikov** [comment]
@rustdesk why did fufesou just delete #8239 ?

**Comment by fufesou** [comment]
@attikov 

I never delete an issue.

Can you provide some screenshots of where you found me deleting it?

Maybe my account was leaked.

**Comment by rustdesk** [comment]
#763

**Comment by attikov** [comment]
@fufesou I apologize, it wasn't you. @rustdesk thank you for the clarification.
