### ISSUE TITLE
Privacy mode on nightly 1.2.4

### ISSUE THREAD

**Issue by Vasilis553** [rustdesk/rustdesk#7343]
### Bug Description

I updated the stable 1.2.3 to nighly 1.2.4 and I changed the windows injector.dll to the one I made with black screen instead of the letters for prevent my laptops screen burns due to hours of work but
When I toogle privacy mode the screen got black for both the host physic screen and the remote side instead of 1.2.3 that blocks only the host phisical side
Version 1.2.3stable:
https://github.com/rustdesk/rustdesk/assets/108126638/8941396f-c43c-4c4e-8249-a023dbe7e52f
Nighly 1.2.4 latest:

https://github.com/rustdesk/rustdesk/assets/108126638/9f482e61-2081-43d2-9169-5820d63efe0f

### How to Reproduce

-

### Expected Behavior

-

### Operating system(s) on local side and remote side

Windows 10-11

### RustDesk Version(s) on local side and remote side

1.2.3stable-1.2.4nighly latest

### Screenshots

-

### Additional Context

-

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
Hi, thanks for your feedback.

I've tried Android (1.2.3 and nightly) --> Win11 (nightly), but failed to reproduce this issue.

Can you please try:
1. Use another PC to connect your remote side, test if there's some pictures. To make sure the issue is caused by the remote side, not the apk.
2. Just do not replace the `injector.dll ` and try again?

**Comment by rustdesk** [comment]
close since its your jindector.dll
