### ISSUE TITLE
Crash: The instruction at 0x00007FF82062930C referenced memory at 0x0000000000000000

### ISSUE THREAD

**Issue by L-U-C-K-Y** [rustdesk/rustdesk#7412]
### Bug Description

We have a couple RustDesk installations that are crashing after a while with the following error:

"The instruction at 0x00007FF82062930C referenced memory at 0x0000000000000000. The operation read could not be performed in memory. Click "OK" to terminate the program."

It happens without connecting to it. After connecting with another remote management tool, I restart the server and things are working again.

<img width="918" alt="image" src="https://github.com/rustdesk/rustdesk/assets/14868134/933dcb8e-0bdb-4b28-af6f-a272f713e0d1">

### How to Reproduce

Unfortunately, I do not know how to reproduce the error, it just happens after a while.

### Expected Behavior

I would expect RustDesk not to crash.

### Operating system(s) on local side and remote side

None on the local side -> Windows 11 on the remote side

### RustDesk Version(s) on local side and remote side

None on the local side -> rustdesk-1.2.3-1-x86_64

### Screenshots

<img width="918" alt="image" src="https://github.com/rustdesk/rustdesk/assets/14868134/933dcb8e-0bdb-4b28-af6f-a272f713e0d1">

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/7342

**Comment by rustdesk** [comment]
Anyhow, try out the nightly build

**Comment by danielmarschall** [comment]
@L-U-C-K-Y You could try running WinDbg to check where the crash happens, and then write the results here. ( Explanation and debug build here https://github.com/rustdesk/rustdesk/discussions/7543#discussioncomment-8947786 ).

Also, please try the nightly build which will be released tomorrow, because RustDesk now uses a new "Flutter" version. Then we could rule out the possibility that the crash was caused by an old Flutter version.
