### ISSUE TITLE
Some of the host key presses are not matching with what remote perceives

### ISSUE THREAD

**Issue by bledatunay** [rustdesk/rustdesk#7530]
### Bug Description

I'm using RustDesk on my laptop running Windows 11, and using it to connect to my Ubuntu cloud instance. Some of the very vital keys to my usage are simply not registering as intended. I did a lot of debugging; messed around with keyboard layouts, re-installed stuff, tried different hosts (MacBook Air, Netbook with Windows 7), tried all keyboard modes (Legacy, Map, Translate), etc. but nothing helped. Combined with the fact that this issue does not occur with another software like TeamViewer or when I use VPN + Windows RDP, tells me that this is a software issue.

Keys that are switched up (out of all the keys on my keyboard):
- "Left Arrow" triggers "Alt R"
- "Down Arrow" triggers "Super R"
- "Right Arrow" does nothing
- "Up Arrow" does nothing, but attempts to take a screenshot
- "Control R" triggers "Page Down"
- "Alt R" triggers "Alternate Enter" (on the Numpad)

Rest of the keys are working just fine. As an additional note, even when I don't touch my physical keyboard and use the On-Screen Keyboard utility of Windows, output is the same.

### How to Reproduce

Press one of those mismatching keys and observe.
(Vastly different hardware gives the same result for me, so I don't think host OS or hardware matters here.)

### Expected Behavior

Proper matching of sent (by host) and received (by remote) keys.

### Operating system(s) on local side and remote side

Windows 11 -> Ubuntu 22.04

### RustDesk Version(s) on local side and remote side

1.2.3-1 -> 1.2.3-1

### Screenshots

![163](https://github.com/rustdesk/rustdesk/assets/17402042/77afcdf6-30db-4c11-8035-64338898064b)

### Additional Context

I have a Turkish Q keyboard, but this shouldn't be a factor regarding the problem because to re-emphasize, this does not happen with Windows RDP or TeamViewer.

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Comment by ITtest1** [comment]
I also encountered a similar problem, I only know that my up button is a screenshot, nothing happens after clicking on the other arrow keys, I don't know the possible effect of the other arrow keys.

Describe the bug
When connecting to Ubuntu Desktop via RustDesk, the arrow keys do not work.

Up Arrow (↑) is interpreted as a screenshot command.

Other arrow keys (↓ ← →) also do not work as expected.


This happens regardless of whether the client is Windows or Android/iOS.

To Reproduce
Steps to reproduce the behavior:

1. On Ubuntu Desktop:

Install XRDP.

Log in via XRDP session.

Inside the XRDP session, install and start RustDesk.



2. On client side (Windows 10 or Android):

Open RustDesk and connect to the Ubuntu Desktop (which is running inside an XRDP session).



3. Try using the arrow keys (↑ ↓ ← →).


4. Notice that:

↑ triggers screenshot instead of Up Arrow.

Other arrow keys also do not behave normally.

Server (Ubuntu Desktop):

OS: Ubuntu 22.04 ＆ 20.04 

Desktop environment: GNOME 

Display server: Xorg

Logged in via: XRDP

RustDesk version: 1.4.0  ＆1.4.1

Client 1 (Windows):

Windows version: 10 

RustDesk version: 1.4.0  ＆1.4.1


Client 2 (Mobile):

Device: Android 

RustDesk version: 1.4.0  ＆1.4.1

Connection type: Internet

Additional context

Issue only occurs when RustDesk is launched inside an XRDP session.

If using LightDM login (auto-login configured) instead of XRDP, arrow keys work correctly with RustDesk. You can even adjust the resolution freely, but you can't adjust the vertical/landscape orientation.

So the problem seems specific to XRDP + RustDesk keyboard mapping.

Tested on both Windows and Android clients → same result.

**Comment by EasyNetDev** [comment]
Hi all, 

I got the same issue using Debian XRDP + Plasma + Rustdesk client connected to a remote Debian X11 Plasma Desktop.
I fixed using this command on both machines:
```
# X11 and XRDP has a problem with default mapping
if [ -x /usr/bin/setxkbmap ]; then
    /usr/bin/setxkbmap -rules base
fi
```

Now on remote one works as it expected. I have on both sides Rustdesk 1.4.9.
