### ISSUE TITLE
Android client file transfer cannot view remote files

### ISSUE THREAD

**Issue by wilinz** [rustdesk/rustdesk#775]
**Describe the bug you encountered:**

Android client file transfer cannot view remote files

<img src="https://user-images.githubusercontent.com/59408438/173597170-2d5a6e09-62ac-4378-b975-d35176d030e8.jpg" width="300px">

**How did you install `RustDesk`?**

GitHub release

**RustDesk version and environment**

1.1.10

**Comment by wilinz** [comment]
The controlled machine is windows

**Comment by rustdesk** [comment]
@Heap-Hop

**Comment by wilinz** [comment]
> @wilinz Does the same thing happen to other controlled device? Could you please try to controll more devices? or use other device to controll the same Windows? And please give us more device info about your current SmartPhone, thx!

I use windows client to test transfer files, it pops up dialog: No active console user logged on,please connectand logon first.
So, I'm guessing, that's why, but I do need to transfer files without logging in. The Android client cannot transfer files while connected, but the premise of transferring files is to log in first. Moreover, the Android client will not prompt you to log in before transferring files like the Windows client, but will not display anything.

**Comment by rustdesk** [comment]
> No active console user logged on,please connectand logon first.

@Heap-Hop we should have the same logic.

**Comment by rustdesk** [comment]
> but I do need to transfer files without logging in

No, we can not do this, for security consideration.

**Comment by ostretsov** [comment]
> No, we can not do this, for security consideration.

Are these limitations present even in the Pro version? We are migrating to RustDesk, but I’m now reconsidering since getscreen.me allows file downloads from a Windows machine that isn't logged in. Because of this feature, we’ll likely keep both applications, as RustDesk does offer better image quality.

Recently, one of our PCs logged out of Active Directory after an update and reboot. We needed to restore functionality quickly, so we copied several binaries from the machine to another using getscreen.me, not RustDesk, due to the "No active console user logged on, please connect and log on first" error. Now, we're dealing with the updated Windows.

I hope you’ll consider adding an extra strategy, at least in the Pro version, to make RustDesk a more universal problem-solving tool.

**Comment by rustdesk** [comment]
@21pages add a strategy option for this, also add to advanced options.

**Comment by rustdesk** [comment]
> Making sense. @21pages add a strategy option for this, also add to advanced options, Pro only. Carefully test, --cm-no-ui for this scenario.

Let's do web client first.
