### ISSUE TITLE
French (azerty) key mapping problem under Windows

### ISSUE THREAD

**Issue by srbPierre** [rustdesk/rustdesk#793]
Hi,

In French Azerty keyboard, under Windows (only) special character like !@$&/  etc...  not working !
But it works if you run the virtual keyboard ?

...

No problem on Android or IOs 

...
Rustdesk 1.1.9  on Windows 10

Thank for help

**Comment by rustdesk** [comment]
But we do not have Azerty keyboard. What type of keyboard mostly used in France?

**Comment by srbPierre** [comment]
this is my virtual keyboard

![azerty_keyb](https://user-images.githubusercontent.com/107108065/174089590-b8de0192-6041-459f-9856-6560ad0c65be.JPG)


Under Linux
# KEYBOARD CONFIGURATION FILE
XKBMODEL="pc105"
XKBLAYOUT="fr"
XKBVARIANT=""
XKBOPTIONS="grp:alt_shift_toggle"

BACKSPACE="guess"

**Comment by srbPierre** [comment]
Virtual Keyb with ALTGR pressed
![azerty_keyb_altgr](https://user-images.githubusercontent.com/107108065/174095358-3e1a4893-00e0-4eaa-ba8e-a6d171c662fc.JPG)

**Comment by asur4s** [comment]
Both sides are Windows? @srbPierre 

I can't reproduce this problem. if both sides are Windows, ALTGR + 0 will get "@". if the remote is Linux, I'm fixing this bug.

**Comment by srbPierre** [comment]
Hi,
it works fine now if both sides are Windows !

Thanks !

**Comment by Coeur-Noir** [comment]
Mmm… have to check version of rustdesk both sides.
Same french keyboard ( azerty ).

Local machine is Ubuntu 22.04 / rustdesk 1.1.9

Distant machine ( remote ) is Windows 10 / rustdesk 1.1.?

If I type [ AltGr ] + [ 0 ] on the local Ubuntu machine, I expect "@" to be printed on the distant Windows machine.

It's "à" that got printed instead - same as if I'd type only [ 0 ] where this [ 0 ] is from the first line of keys ( ie. not from numeric pad. )

**Comment by asur4s** [comment]
It is recommended to use the latest rustdesk

**Comment by Coeur-Noir** [comment]
Checking done, it's v1.1.9 on all machines.

**Comment by rustdesk** [comment]
#1547

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/1518

**Comment by ericpodico** [comment]
With a french keyboard, when logging in Windows 10, I cannot use the "6" or "8", 
the displaid letter will be "as if" i did not press the shift to get my 6 or 8.
I still can use the NUM pad to get a 6 or an 8, but some mini laptop (mac) do not have any NUM Pad

**Comment by TKMankind** [comment]
I found 2 issues with AZERTY layout.

1)
First, there is no support for the symbols ¨^ who have a dedicated key on our keyboards.

See this layout. It is at the left of the main ENTER/ENTREE key, you will find them in red on one key : 
![image](https://github.com/rustdesk/rustdesk/assets/8639768/572cd214-d04d-4fe5-a939-ec66739e07e3)

This is a very special key in the AZERTY layout. Press it, and nothing will happen... because the computer is waiting for you for the second key, where the symbol must be applied.

For example, if I want the "ô" like in the french word "impôts" (taxes), I must press the "¨^" key, release it, and press the "o" one.
For the funny story, if I do it to an unsupported letter in the french language, like "p", I will get "^p" :)

And if I want to get the "¨" like for the word "noël", I must press SHIFT+"¨^", release them, and the "e" one.

ALT CODES doesn't work.

The issue was reproducted on VMs and real hardware.

2)
On the Legion laptop of a friend I helped today, pressing a number on the numpad while the NumLock is activated will cause the appareance of the NumLock indicator, this at EVERY number pressed. I mean this :
![image](https://github.com/rustdesk/rustdesk/assets/8639768/068e7f7b-7095-49cc-9570-ae0bb460367e)
This is also the case with the Capslock indicator, when I pressed a number while CapsLock is activated : 
![image](https://github.com/rustdesk/rustdesk/assets/8639768/d6c6a6e5-3ef8-42f8-b9f5-745c5a06031e)

I think this is because of the _Lenovo Vantage_ software, but I can't be sure of that as I can't keep the control of said laptop all the time for my personal enjoyment :)
