### ISSUE TITLE
cannot use up,right,down,left button when using vim on putty

### ISSUE THREAD

**Issue by guijuzhejiang** [rustdesk/rustdesk#796]
when i use putty for linux ssh, I clicked the up,right,down,left button but i got  4 ,6 ,8 ,2 in vim.
nano have no such bug.

**Comment by advorsky73** [comment]
same when using vmware workstation running an ubuntu on the remote machine.

**Comment by asur4s** [comment]
Can you provide more detailed information( [Issue Template](https://github.com/rustdesk/rustdesk/issues/new?assignees=&labels=bug&template=bug_report.md&title=) )? So that we can better reproduce this bug.

**Comment by pogisanpolo** [comment]
**Describe the bug you encountered:**

When connecting to a Linux server via SSH using putty, and attempting to edit a text file using `vim`, arrow keys (up, left, down, right), or the del, home, and end keys, they do not navigate, but opens the help in vertical split instead. Something similar happens when using `nano`, where the screen shifts quickly as though a different screen was opened, then immediately closed.

**What did you expect to happen instead?**

Using the aforementioned navigation keys would move the cursor to the desired position. E.g: Home to the beginning of the line, End to the end of line, etc.


**How did you install `RustDesk`?**


From the installer provided in `rustdesk.com`.

---

**RustDesk version and environment**


Remote machine: Windows 10 Professional, Rustdesk version: v1.1.9
Local machine: Windows 10 Home, Rustdesk version: v1.1.9

**Comment by asur4s** [comment]
I reproduced this bug in the latest version. 

#1681

**Comment by rustdesk** [comment]
close as duplicate
