### ISSUE TITLE
harmonyos compatibility

### ISSUE THREAD

**Issue by 516492043** [rustdesk/rustdesk#849]
当我在鸿蒙2.0系统（兼容安卓10版本）下使用RustDesk1.19时，我的手机无法显示或启用语音服务，请帮忙修复，谢谢！
![20220623_160224_837](https://user-images.githubusercontent.com/96425553/175248369-0ba6447c-ea8a-437d-b2b0-49628982eacb.jpeg)
![20220623_160229_883](https://user-images.githubusercontent.com/96425553/175248410-204ed62a-e899-4d98-947f-aee39f88aad6.jpeg)

**Comment by 516492043** [comment]
如果有大神看到后并修复了此问题，不必回复我，我是小白一个，不会编程，不懂英语，github很多东西都搞不懂，如果发帖有发错的地方还望大佬见谅，谢谢！

**Comment by rustdesk** [comment]
@Heap-Hop yesterday i sent you

**Comment by Heap-Hop** [comment]
@516492043 
Maybe you need to upgrade HarmonyOS 2.0.1.

I checked with https://developer.huawei.com/consumer/cn/agconnect/cloud-adjust/ 

And noticed:
HarmonyOS 2.0.0 only works with Android 9 API, and 2.0.1 can use Android 10 API.

你可以试一下更新到HarmonyOS 2.0.1
我测试了2.0.0只能适配安卓9，2.0.1就可以使用安卓10的API了。

**Comment by 516492043** [comment]
> @516492043 也许你需要升级和谐OS 2.0.1。
> 
> 我查过了 https://developer.huawei.com/consumer/cn/agconnect/cloud-adjust/
> 
> 并注意到： 和谐OS 2.0.0仅适用于Android 9 API,2.0.1可以使用Android 10 API。
> 
> 你可以试一下更新到HarmonyOS 2.0.1 我测试了2.0.0只能适配安卓9，2.0.1就可以使用安卓10的API了。

你好，据我所知，目前华为手机的鸿蒙系统版本都在2.0.0.XXX版本，今天刚更新到最新版本依然是2.0.0XXX版本（请看下图），这就意味这有大概有2亿左右的华为用户无法正常使用RustDesk应用，华为手机鸿蒙3.0开发者内侧于2022年6月15日开始报名，距离公测或者或者正式版推送保守预计最少还要3个月的时间（这些还只是新机型），老机型保守估计5个月以后了，所以我有一个想法（只是建议），大神可以在下一版本加入安卓9.0的API，或者单独开发一个鸿蒙版本比较好，因为现在鸿蒙系统也有超过3亿的用户，在移动终端可称为世界第三大操作系统，并且用户量还在不断递增，大神可以酌情考虑。
![Screenshot_20220623_183752_com huawei android hwouc](https://user-images.githubusercontent.com/96425553/175295297-769eaac6-74d6-48a2-a2f7-cbe7cc323e16.jpg)

**Comment by 516492043** [comment]
> @516492043 也许你需要升级和谐OS 2.0.1。
> 
> 我查过了 https://developer.huawei.com/consumer/cn/agconnect/cloud-adjust/
> 
> 并注意到： 和谐OS 2.0.0仅适用于Android 9 API,2.0.1可以使用Android 10 API。
> 
> 你可以试一下更新到HarmonyOS 2.0.1 我测试了2.0.0只能适配安卓9，2.0.1就可以使用安卓10的API了。

众所周知，因为华为至少关闭root通道，所以用户系统的升级只能跟随官方推送，无法绕过官方渠道自行升级更高的版本级别，请理解！

**Comment by Heap-Hop** [comment]
@516492043 
Thanks for your advice.

1. We should be talking about `System Sound Recording for Android 9 API`, not only HarmonyOS 2.0.0. We use `AudioPlaybackCapture API` which behaves completely differently on Android 9 and Android 10. 
It has bad experience on Android 9. see [here](https://developer.android.com/guide/topics/media/playback-capture)
We haven't found a suitable solution for `System Sound Recording` on Android 9 yet. :(  
Please let me know if there is a good solution for Android 9 or HarmonyOS specifically (not adb or root).
And contributions welcome!


>语音服务
2. If you mean `voice intercom` instead of `system audio recording`, see #188

**Comment by sunfrank1987** [comment]
在鸿蒙OS 2.0.0 内录声音问题：
1. build.gradle 设置 targetSdk 29
2. 去掉 这个application android:allowAudioPlaybackCapture="true"
二选一都可以，就可以采集到声音了

**Comment by rustdesk** [comment]
close to favor https://github.com/rustdesk/rustdesk/issues/3893
