### ISSUE TITLE
Keyboard stops working if mouse is not moved for a few seconds. Must wiggle mouse for keyboard to begin working again.

### ISSUE THREAD

**Issue by msftsecurityteam** [rustdesk/rustdesk#8768]
### Bug Description

I am remoting into a Linux workstation and I am a heavy user of the terminal. It is very annoying, but I would say after approcximately 5 seconds of mouse inactivity, the keyboard stops working on the remote host. If I wiggle the mouse, then the keyboard begins working again. This typically allows me to do one command per mouse wiggle before I am unable to use the keyboard.

### How to Reproduce

1. Open terminal
2. Stop using mouse for 5-10 seconds

### Expected Behavior

If the repro steps are followed, then the terminal stops having characters written to it because the keyboard now is not functioning properly.

### Operating system(s) on local side and remote side

Debian 11 -> Debian 12

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

N/A

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by rustdesk** [comment]
wayland? please give more details about your debian 11.

**Comment by msftsecurityteam** [comment]
Client: Debian 11 running awesomewm (X11)
Server: Debian 12 running default XFCE from installation (X11)

I had the client upgraded to 1.2.7 for a while now (no change) and just upgraded the server rustdesk. I still have not noticed any improvement with this issue. One observation: I notice that the hidden menubar on the bottom of the XFCE4 desktop (with the icons of common apps that I run, like the "start" menu for XFCE) unhides itself as this bug manifests. Meaning, it's as if the mouse was pulled down to the menubar (thus, unhiding it) right before the keyboard stops working.

Not running Wayland on either side.

**Comment by msftsecurityteam** [comment]
Was this ever fixed? I updated my Rustdesk to the latest version and it still happens...

**Comment by jjolmo** [comment]
I can reproduce the exact same behaviour

Mint X11 (1.2.3) > Debian X11 (1.2.3)

It just happened out of nowhere very recently. Btw, thanks for the "wiggle" trick to solve it. I cannot say I can work with it, but confirmed that both of our setups using STABLE versions with debian have the same issue

**Comment by jjolmo** [comment]
@msftsecurityteam This issue is driving me nuts. But I discovered other bad behaviours lately. My setup is Linux Mint. Some of the examples:
- Any chromium based browser: Go to any page like reddit with a large page size, so the scroll happens. Start scrolling the mousewheel without moving an inch the cursor. Suddenly the mousewheel just stops working
- Some inputs in some apps, like Godot editor: It let's you type and after 2-3 seconds the focus just loses

I'm still investigating because I'm just about to format everything, but I suspect the issue might come from the private AMD PRO Driver, which I installed to perform some specific tasks. Is this your case, too? 

Thanks
