### ISSUE TITLE
Flatpack Support ?

### ISSUE THREAD

**Issue by Cloud-Kid** [rustdesk/rustdesk#898]
Hi !

WIth the recent rise of the Flatpack package format, I think supporting this kind of package is interesting. As I am not a developer, I don't know if it is doable/easy but I think this will be a munch appreciated addition. 

I know this can take more of your development time but ever if it involve to remplace the .Appimage format, I think this is far more interesting.

Love your app, thanks for your work !

Cloudkid

**Comment by farribeiro** [comment]
I worked on a yaml for rustdesk these days, to no avail.with two approach, using appimage (I believe it is ideal due to the absence of a daemon) not execute the app, and compile (occurs a error building rustdesk app, not the dependencies) but I don't know how I prefix the installation with vcpkg/cargo

My yaml file https://github.com/farribeiro/built-flatpaks/blob/main/com.rustdesk.rustdesk.yml

**Comment by rustdesk** [comment]
It is Flatpak.

dup: https://github.com/rustdesk/rustdesk/issues/459

**Comment by Cloud-Kid** [comment]
Sorry about the duplicate, and thanks for your work again !

Yeah, I mean adding it as a downloadable package, from what I can see, there is no flatpack package option available in the ["releases"](https://github.com/rustdesk/rustdesk/releases) section on GitHub or in the flatpak/flathub repository. 

I will keep talking [in the other thread](https://github.com/rustdesk/rustdesk/issues/459) from now on.
