### ISSUE TITLE
IP v6?

### ISSUE THREAD

**Issue by open-trade** [rustdesk/rustdesk#98]

**Comment by scarab714** [comment]
I'm also blocked because of the lack of ipv6 support for rustdesk.
My domain is answering with both ipv4 / ipv6 ip ( andcannot be changed) so I cannot use it with Rustdesk. I have to put my ipv4 manually (knowing that it is changing with my connection).
My dyndns domain is also sending ipv6 so I can't have a name with only ipv4.

It would be nice to have get ipv6 support knowing that it's being use more and more and everywhere.
